### ISSUE TITLE
Bismark methXtract to use n/3 cpus instead of n/10

### ISSUE THREAD

**Issue by jsl26** [nf-core/methylseq#116]
Hi Phil,

Thank you for this pipeline it is extremely helpful and has been a huge help so far in my PhD project!

I think the multicore calculation for bismark Methylation extraction is incorrect in the main.nf line 645.

The script defines each multicore as no.CPUs /10 for the methylation extraction however looking at the Bismark documentation this should be no.CPUs/3:

> `--multicore <int>` Sets the number of cores to be used for the methylation extraction process.
>
> If system resources are plentiful this is a viable option to speed up the extraction process (we
observed a near linear speed increase for up to 10 cores used). Please note that a typical process of extracting a BAM file and writing out '.gz' output streams will in fact use ~3 cores per value of `--multicore <int>` specified (1 for the methylation extractor itself, 1 for a Samtools stream, 1 for GZIP stream), so `--multicore 10` is likely to use around 30 cores of system resources. This option has no bearing on the speed of the `bismark2bedGraph` or genome-wide cytosine report processes

I think this explains why despite feeding the job 24 CPUs and 128GB RAM and specifying this in the config file only 2 multicores were used. Looking at the pipeline report only 4CPUs and 23GB RAM were utilised for the process and it took over 23hours to run on a human sample with 72 million paired reads. In contrast the Bismark alignment process finished in 9 hours and used 12 CPUs and 80GB RAM (hg37d5 as reference) running with 8 multicores. 

Actually on this note, i wonder whether the smaller human reference genome and the figures above suggest a different cpu_per-multicore strategy might be possible e.g. 2 cpus per multicore for smaller genomes?

thanks

Joe

**Comment by ewels** [comment]
Hi @jsl26,

Thanks for opening this issue - it's a good one to look in to. To spell out what the pipeline is doing, here is the relevant code:

https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/main.nf#L642-L649

The default config gives 12 cpus:

https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/conf/base.config#L44-L48

So yes, as you say - 12 cpus / 10 ends up as multicore 1 (not specifying `--multicore`). And on a automatic retry with 24 or a custom config, then 24 cpus would end up as `--multicore 2`.

I wrote this code a while ago and obviously thought that I was following instructions from @felixkrueger, based on my comment:

> `// Numbers based on Bismark docs `

But yes, I agree - dividing by 10 does seem a little excessive and not in line with the (current) docs! So we should change it to divide by 3 instead.

> I wonder whether the smaller human reference genome and the figures above suggest a different cpu_per-multicore strategy might be possible e.g. 2 cpus per multicore for smaller genomes?

I'm not sure I really understand you here. I don't really see how genome size affects things - if we have a certain number of cpus available I think we should just use them as much as possible.. (If people routinely run with smaller genomes they can set the config to request fewer cpus).

Phil

**Comment by jsl26** [comment]
Hi Phil,

Thank you for responding to this so quickly!

Sorry I wasn't very clear with the second point where I was referring to the multicore parameters for Bismark alignment. The multicore strategy for alignments was based on the mouse genome (sorry i don't know how to do the neat thing you did with nested code):

    ```
    // Try to assign sensible bismark memory units according to what the task was given
        multicore = ''
        if( task.cpus ){
            // Numbers based on recommendation by Felix for a typical mouse genome
            if( params.single_cell || params.zymo || params.non_directional ){
                cpu_per_multicore = 5
                mem_per_multicore = (18.GB).toBytes()
            } else {
                cpu_per_multicore = 3
                mem_per_multicore = (13.GB).toBytes()
            }
```

With this setting i was utilising 12 cpus and 80gb of ram despite specifying the following in the config file. 
```
 withName:bismark_align {
     cpus = 24
memory = 128.GB
}
```
The report suggested 8 multicore processes had been requested. I wondered therefore whether this figure of cpu_per_multicore=3 could be reduced to increase multicore number to utilise max available resources.

I am hoping to analyse a slightly larger data set without imposing too much on our compute cluster hence the drive to squeeze maximum mileage out of the resources fed.

On a similar vein the other major process that takes up a significant amount of time for me is trimgalore. I saw on the trimgalore site (https://github.com/FelixKrueger/TrimGalore/pull/39) that multithreading using pigz increases the speed significantly and utilises the available resources. I wasn't sure if this version/option was part of the pipeline since the report suggests only 2 cpus being used for the process. sorry i can raise this as a separate issue if this is inappropriate?

thanks again,

joe

**Comment by jsl26** [comment]
Hi Phil,

Thank you for responding to this so quickly!

Sorry I wasn't very clear with the second point where I was referring to the multicore parameters for Bismark alignment. The multicore strategy for alignments was based on the mouse genome (sorry i don't know how to do the neat thing you did with nested code):
`// Try to assign sensible bismark memory units according to what the task was given
    multicore = ''
    if( task.cpus ){
        // Numbers based on recommendation by Felix for a typical mouse genome
        if( params.single_cell || params.zymo || params.non_directional ){
            cpu_per_multicore = 5
            mem_per_multicore = (18.GB).toBytes()
        } else {
            cpu_per_multicore = 3
            mem_per_multicore = (13.GB).toBytes()
        }`

With this setting i was utilising 12 cpus and 80gb of ram despite specifying the following in the config file. 
`withName:bismark_align {
cpus = 24
memory = 128.GB
}`

The report suggested 8 multicore processes had been requested. I wondered therefore whether this figure of cpu_per_multicore=3 could be reduced to increase multicore number to utilise max available resources.

I am hoping to analyse a slightly larger data set without imposing too much on our compute cluster hence the drive to squeeze maximum mileage out of the resources fed.

On a similar vein the other major process that takes up a significant amount of time for me is trimgalore. I saw on the trimgalore site (https://github.com/FelixKrueger/TrimGalore/pull/39) that multithreading using pigz increases the speed significantly and utilises the available resources. I wasn't sure if this version/option was part of the pipeline since the report suggests only 2 cpus being used for the process. sorry i can raise this as a separate issue if this is inappropriate?

thanks again,

joe

**Comment by ewels** [comment]
> sorry i don't know how to do the neat thing you did with nested code

Triple back ticks for code blocks, single back ticks for inline code, see https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by ewels** [comment]
> On a similar vein the other major process that takes up a significant amount of time for me is trimgalore.

Yup, just done in https://github.com/nf-core/methylseq/pull/120 - will be released very soon.

**Comment by ewels** [comment]
> I wondered therefore whether this figure of `cpu_per_multicore=3` could be reduced to increase multicore number to utilise max available resources.

Yes - I wonder if we could make this configurable. Have a `params.bismark_align_cpu_per_multicore` and `params.bismark_align_mem_per_multicore` (catchy!) and use these if supplied instead of guessing.

**Comment by ewels** [comment]
I've made a new issue for this at https://github.com/nf-core/methylseq/issues/124 - I'll close this issue now as the methXtract stuff is done and merged 👍

**Comment by jsl26** [comment]
great thank you so much for all above!
