### ISSUE TITLE
Write defaults value in help message

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#118]
Hey,

I think writing the default values of parameters will help mmuch when getting the help message.

Thanks!

**Comment by ewels** [comment]
Agreed 👍 

We have already done this in other pipelines and intend to auto-generate this help soon (with default values). But short term, we should add this.

Phil

**Comment by efratushava** [comment]
Great, thanks

**Comment by ewels** [comment]
Apologies, it was the argument _types_ that we added to other pipelines. And this one apparently.

I'm actually less keen to add the default values now that I look at it. Nearly all flags are optional, so their defaults are `false` or whatever the underlying tool has as a default. So I'm not sure that just specifying the default value would be very helpful. Giving more verbose help makes the help text longer and harder to read and duplicates what is already written in the [usage documentation](https://github.com/nf-core/methylseq/blob/master/docs/usage.md).

@efratushava - could you give an example of how you would like the command line help text to read?

Phil

**Comment by efratushava** [comment]
Yeah that's right

I don't know. I just know that when i wanted to run the pipeline I had to enter the config file to check what is the default (for example-in skip_deduplication,non_directional,outdir etc.)

Thanks anyway!

**Comment by ewels** [comment]
Sure - yes I would encourage people to read the docs for this. Hopefully that has all of the defaults and more explanation. Let me know if you find anything missing there.

Note that if you use the [`nf-core launch` helper](https://nf-co.re/tools#launch-a-pipeline) then it takes you through all of the parameters and gives you a description and shows the default 👍
