### ISSUE TITLE
--cytosine_report for bismark_methXtract

### ISSUE THREAD

**Issue by noirot** [nf-core/methylseq#129]
Hello,

for downstream analysis I need the strand of each cytosine. To get it I would like to add `--cytosine_report` in comand line bismark_methylation_extractor and to save outputs `*.CpG_report.txt.gz` in `results/bismark_methylation_calls/stranded_CpG_report`

If you are ok with this enhancement I can develop it and make a PR ?!
Céline

**Comment by ewels** [comment]
Hi @noirot,

Absolutely! Good idea. Should be possible to make it optional with a new Nextflow param..

Phil
