### ISSUE TITLE
Add option to change max number of cpus, memory etc.

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#135]
Running the pipeline (using bwa-meth aligner), I get the following message:
```
Error executing process > 'qualimap (248933-cf-M.ben_list.b37)'

Caused by:
  Process requirement exceed available CPUs -- req: 12; avail: 10
```

Can you add an option to specify number of maximum cpus to use?

**Comment by ewels** [comment]
We already did that. See the docs: https://github.com/nf-core/methylseq/blob/master/docs/usage.md#--max_cpus

**Comment by efratushava** [comment]
I'm sorry.. 

Thanks!

**Comment by ewels** [comment]
No problem - great minds think alike I guess! :wink:
