### ISSUE TITLE
Changing "picard" to "bwa-mem_markDuplicates"

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#138]
Am I right to say that the directory in the given line (from the multiqc process) is supposed to be `bwa-mem_markDuplicates`?

https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/main.nf#L970

**Comment by ewels** [comment]
Hi @efratushava,

Sorry for the very late reply to your issue. The pipeline code is correct as it currently. `ch_markDups_results_for_multiqc` is the Nextflow channel name, `bwa-mem_markDuplicates` is the directory name for the published output files.

No change to the pipeline code is needed, I believe that this is working as intended.

Phil
