### ISSUE TITLE
Running methyseq with bwa-meth: methyldackel run only on one sample

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#139]
I'm trying to run the pipeline using "bwameth" aligner.

The command is this:
```
nextflow -log methylseq_bwameth run -r dev -w work_try  nf-core/methylseq -with-singularity /tmp/singularity/methylseq_1.1.img -profile singularity --aligner bwameth  --reads 'data/run/fastq_files/links/*sorted_{1,2}.fastq' --name try_biscuit_pipeline --save_reference --genome hg38 --fasta  Genomes/hg38/bwa-meth/hg38.fa  --fasta_index data/Genomes/hg38/hg38.fa.fai --bwa_meth_index Genomes/hg38/bwa-meth/hg38.fa  --max_cpus 8 --skip_trimming --max_memory '60GB'
```

Everything works fine, until the `methyldackel` step. It's working only on one sample!
The end of the log is here:
```

executor >  local (22)
[ba/f84f0d] process > get_software_versions          [100%] 1 of 1 ✔
[48/040213] process > fastqc (149122-exo-X-60min.... [100%] 3 of 3 ✔
[31/e89b79] process > bwamem_align (149122-exo-X-... [100%] 3 of 3 ✔
[f5/30f105] process > samtools_sort_index_flagsta... [100%] 3 of 3 ✔
[d3/b6e063] process > markDuplicates (149122-exo-... [100%] 3 of 3 ✔
[07/8b5889] process > methyldackel (248933-cf-M.b... [100%] 1 of 1 ✔
[18/bac7a5] process > qualimap (149122-exo-X-60mi... [100%] 3 of 3 ✔
[85/1d3205] process > preseq (149122-exo-X-60min.... [100%] 3 of 3 ✔
[cc/a4a896] process > multiqc                        [100%] 1 of 1 ✔
[78/9bb626] process > output_documentation           [100%] 1 of 1 ✔
[0;35m[nf-core/methylseq] Pipeline completed successfully
Completed at: 22-Dec-2019 15:04:39
Duration    : 6m 40s
CPU hours   : 0.7
Succeeded   : 22
```

From some attempts I made, I think the problem is because the `methyldackel` step get a fasta as input, and somehow it makes him running only once.

Can someone help me?

**Comment by drpatelh** [comment]
Copied from #help on Slack

Yes, that looks like a bug with that process.

```
file bam_index from ch_bam_index_for_methyldackel.collect()
file fasta from ch_fasta_for_methyldackel.collect()
file fasta_index from ch_fasta_index_for_methyldackel.collect()
```

There should be a collect() at the end of all of the input lines above.

**Comment by robsyme** [comment]
Adding a collect() will collapse all three of efratushava's bam files into an array and run the methyldackel process once.
If `bam_index` contains an array of bam files, the line:
https://github.com/nf-core/methylseq/blob/40760ecffbf1d3ce8659712f692454ed88e59324/main.nf#L875
Is going to cause problems.

My reading of the pipeline suggests that the methyldackel needs to be run once per bam file. I've submitted a PR https://github.com/nf-core/methylseq/pull/140 that seeks to address the problem.

**Comment by phue** [comment]
Closing this because it was fixed in https://github.com/nf-core/methylseq/pull/140

Thanks @robsyme
