### ISSUE TITLE
Make fastqc time longer

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#143]
Hi,

The time for fastqc is not enough...
I'm getting the following error:
```
Error executing process > 'fastqc (TBR532u)'

Caused by:
  Process exceeded running time limit (2h)

Command executed:

  fastqc --quiet --threads 1 TBR532u.R1.fq.gz TBR532u.R2.fq.gz

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /path/to/work/68/387258828eecd198130d8230217c21

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

Can you please give it longer running time? Or give it more than one thread?

Thanks!

**Comment by ewels** [comment]
Hi @efratushava,

Thanks for the issue! I agree that this is a bit small and we should increase the default. If you'd like to submit a pull-request that would be very welcome! It's quite an easy change.

In the short term, you can overwrite the defaults with your own configuration file - see the [docs](https://nf-co.re/usage/configuration#custom-configuration-files).

Something like this should do the job:

```nextflow
process {
  withName:fastqc {
    cpus = 4
    time = 16.h
  }
}
```

Save that to a file called `~/.nextflow/config`, or any file and specify it with the `-c` command line flag and it should extend the resources given to FastQC.

Phil

**Comment by phue** [comment]
Fixed with https://github.com/nf-core/methylseq/pull/195/commits/5f9d55e3a7a91c432100782380a9589b98c3ee27
