### ISSUE TITLE
Workflow runs in my home but not in scratch

### ISSUE THREAD

**Issue by littleblackfish** [nf-core/methylseq#144]
Hello, 

I am attempting to replace some archaic make based workflows with nf-core/methylseq. I am pretty green with nextflow but also pretty sure something funny is going on here. I am just trying to run the test profile with 

`nextflow run nf-core/methylseq -profile test,conda` 

and it runs fine in my home directory with minor errors at preseq process (?). But when I try to do the same exact thing from my scratch dir (another filesystem) I get this error: 

(Note that I first got this error with singularity, and tried to set `singularity.autoMounts = true` but no dice, then I noticed I am getting the same exact error with conda. Also, I use singularity with custom binds on this cluster all the time. ) 

I have no idea where to go from here. 

```
Error executing process > 'output_documentation'

Caused by:
  Process `output_documentation` terminated with an error exit status (127)

Command executed:

  markdown_to_html.r output.md results_description.html

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: markdown_to_html.r: command not found

```

**Comment by littleblackfish** [comment]
Ok, I noticed that I had `singularity.enabled = true` in my nextflow.config so it was defaulting to singularity even with `-profile conda` so this problem is specific to singularity, nevertheless it is still there with `singularity.autoMounts = true`. Any input would be appreciated.

**Comment by drpatelh** [comment]
Hi @littleblackfish I would check file permissions because that script is shipped in the `bin/` directory of the pipeline and and should be executable and available on the `$PATH` when Nextflow runs. 

Alternatively, have you tried adding an additional bind path for Singularity to find your other mount? e.g.
https://github.com/nf-core/configs/blob/b23e9d5a9f8772d83acfdf0dfb8c9d68de5d8087/conf/genouest.config#L11

**Comment by littleblackfish** [comment]
Thanks for the input, yes, I did definitely try to `singularity.runOptions` trick, to no avail. Interestingly, I myself can't find the `markdown_to_html.r` script inside the container, neither the one pulled by nextflow nor the one I pulled manually from dockerhub. Despite that, the container performs as expected on 3 different machines, but not on this cluster's scratch filesystem. Good news is that I got it to work using conda, but I am totally flustered with singularity at this point.

**Comment by drpatelh** [comment]
Ah, no that script will be part of the pipeline code that would have been pulled automatically when you ran `nextflow run nf-core/methylseq`. It should be in `~/.nextflow/assets/nf-core/methylseq/bin/`. If it's working with Conda then I would suspect it's something to do with the Singularity bind paths not being available in the container when you run the pipeline.

**Comment by littleblackfish** [comment]
I am now cross examining the .command.run files in the working vs non-working versions. The way binds are done, both have access to the same filesystems. I check $PATH just before the nxf_launch line where `singularity exec` is actually being run, and get this: neither has `~/.nextflow/assets/nf-core/methylseq/bin/` in there. It must be appended after the container is spun up somehow (?), and it works as expected if the work dir is in my home but not if it is on a network mount. 
I am looking at the docker file, it is essentially the conda env and nothing more, and there is no singularity recipe. At this point I frankly do not understand how this is running when workdir is in my home either. Wherever this PATH is being built, just fails for my set-up , which I believe is not uncommon, it is a large edu cluster after all. Help me figure this out please?

**Comment by drpatelh** [comment]
I swear I just got an alert suggesting you had messaged again @littleblackfish ?! :sweat_smile: Did you fix it? If not, can you join the `methylseq` channel on the nf-core Slack workspace please? Just easier to message in real time there to troubleshoot issues.
https://nf-co.re/join

**Comment by littleblackfish** [comment]
Hello, yes and no. 

Here is the deal, the /home dir on this machine is apparently symlinked from another network mount. When I run the workflow from ~ , all is well, but when I am running from the scratch (another network mount, say /scratch)  `nxf_container_env` refers to the symlinked home and I cannot, for the life of me, get singularity to bind the right paths, even if I put the -B option in there by hand.

I can workaround either by explicitly setting NXF_HOME to the actual home path, or using conda runtime instead of singularity. 

Overall, looks like it is very much possible to confuse the singularity bind logic beyond recovery with a strategically placed symlink. Took me 2 days to figure out what is going on, I think this might be a dealbreaker for the more bio-inclined user. 

Next time I'm running in circles I'll hop on to the slack channel.

**Comment by ewels** [comment]
Ok, closing the issue for now - shout if you'd like it reopened 👍 

Phil
