### ISSUE TITLE
How to get specific version e5f229c?

### ISSUE THREAD

**Issue by noirot** [nf-core/methylseq#149]
Does there is a way to get the dev version of the commit e5f229c, where I added a parameter ?

I would like to 'distribute' it to a biologist :/, if it possible to do it directly with nextflow ? Or could you create a tag ?

Thanks

**Comment by noirot** [comment]
Found  nextflow pull nf-core/methylseq -r e5f229cd7c43ee1f9dd1b8188c295dc7f9206cd9

**Comment by ewels** [comment]
Yes sorry, we desperately need to fix up the current `dev` branch and push a release...
