### ISSUE TITLE
Preseq failing most of the time

### ISSUE THREAD

**Issue by ewels** [nf-core/methylseq#161]
Anyone running the pipeline will be familiar with this log message:

```
terminated with an error status (1) -- Error is ignored.
```

Preseq has a history of failing a lot, especially for small or low complexity files. But it seems to be failing a _lot_ now, maybe all of the time. This needs investigating.

Phil

**Comment by ewels** [comment]
Yup! The pipeline already has that set as default so you shouldn't need to set that in any additional configs:

https://github.com/nf-core/methylseq/blob/03972a686bedeb2920803cd575f4d671e9135af0/conf/base.config#L59-L61

It would be nice to try to get it to fail a little less though 😅

**Comment by bsiranosian** [comment]
Oh good, I didn't notice that. I'm not sure why my whole run failed then.

**Comment by apeltzer** [comment]
Later preseq versions received some updates to fail more gracefully, so if you upgrade the preseq version a bit, you should be fine 👍🏻

**Comment by ewels** [comment]
I think we're already on 3.1.2 which is quite recent. Do you know when those versions went out? I still see the same failures on every test run.

**Comment by ewels** [comment]
It's tempting to update the config to allow the error exit code, so that we don't always get the pipeline report saying that the pipeline completed with errors (which always worries me / others).

**Comment by ewels** [comment]
Using BED files instead of BAM, as suggested in https://github.com/nf-core/methylseq/issues/96#issuecomment-716986814 could also potentially help..

**Comment by Rohit-Satyam** [comment]
I tried the BED file as input but it still fails


```
PAIRED_END_BED_INPUT
  TOTAL READS     = 14155
  DISTINCT READS  = 14006
  DISTINCT COUNTS = 5
  MAX COUNT       = 94
  COUNTS OF 1     = 13956
  MAX TERMS       = 2
  OBSERVED COUNTS (95)
  1	13956
  2	46
  3	1
  5	2
  94	1
  
  ERROR:	max count before zero is less than min required count (4) duplicates removed
```

**Comment by Tesalonius** [comment]
Hello everyone. Have you managed to find a solution to this problem? I have been running the test on methylseq and getting 2 failed processes "terminated with an error exit status 1". Also getting an error "terminated with an error exit status 139", all in the preseq stage.
I'm new to using nf-core so if anyone has any tips of troubleshooting, it would be greatly appreciated.
Thanks

**Comment by bounlu** [comment]
May I suggest to implement to run in `defect` mode as suggested by Preseq developer when the number of reads is >50M?

`ERROR: too many defects in the approximation, consider running in defect mode`

https://github.com/smithlabcode/preseq/issues/29

**Comment by sateeshperi** [comment]
@bounlu does the defect run mode fix this issue ?

**Comment by bounlu** [comment]
Sometimes yes, but not always. It may still fail in `defect` mode.

**Comment by sateeshperi** [comment]
i see, any recommendations on what can be done or should we mark this as expected and close the issue ?

**Comment by mahesh-panchal** [comment]
Does https://gatk.broadinstitute.org/hc/en-us/articles/360037591931-EstimateLibraryComplexity-Picard accomplish the same thing?
