### ISSUE TITLE
Qualimap fails with big samples

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#169]
I have a problem with qualimap, it fails with big bam files, no matter how much memory and CPUs I give. (I can't give more then 256G due to cluster limits...)

What can I do?

**Comment by ewels** [comment]
Please could you provide some more information about how it fails, the command that you are using and any other relevant information?

We have an issue template for reporting bugs but it has recently stopped working (a fix is on the way). In the meantime, you can see the template here: https://github.com/nf-core/methylseq/blob/master/.github/ISSUE_TEMPLATE/bug_report.md - this has all of the typical questions that we need to be able to help.

**Comment by ewels** [comment]
Also, questions like this are better asked on the nf-core Slack `#methylseq` channel rather than as GitHub issues. You'll get much faster responses there and we can take it as a quicker discussion.

**Comment by ewels** [comment]
Closing to due lack of responses.
