### ISSUE TITLE
Methylseq: Convert parameter docs to JSON schema

### ISSUE THREAD

**Issue by apeltzer** [nf-core/methylseq#189]
Hi!

this is not necessarily an issue with the pipeline, but in order to streamline the documentation group next week for the hackathon, I'm opening issues in all repositories / pipeline repos that might need this update to switch from parameter docs to auto-generated documentation based on the JSON schema.

This will then supersede any further parameter documentation, thus making things a bit easier :-)

If this doesn't apply (anymore), please close the issue. Otherwise, I'm hoping to have some helping hands on this next week in the documentation team on Slack https://nfcore.slack.com/archives/C01QPMKBYNR

**Comment by tmuylder** [comment]
First check done, I'll request a review in a sec. 

Missing information on parameters defined in `main.nf`, however related to trimming with `trimmomatic` so I've put them in that group: 
```
    Trimming presets:
     --pbat [bool]
     --single_cell [bool]
     --epignome [bool]
     --accell [bool]
     --zymo [bool]
     --cegx [bool]
```

Missing information from `nextflow_schema.json`:
```
- `name`
- `project`
```

Additional remarks: 
- `meth_cutoff` requires an integer according `main.nf`, yet its default is defined as boolean False in `nextflow.config`
- `known_splices` idem: false vs string
- `bismark_align_cpu_per_multicore` idem: null vs int (default: 3)
- `bismark_align_mem_per_multicore` idem: null vs str (default: "13.GB")

**Comment by apeltzer** [comment]
Ping @phue to comment on the above maybe ...?

**Comment by phue** [comment]
Hi @tmuylder,

apologies for the slow response, somehow missed the ping(s).
Thanks for picking this up, I think the schema really needed somework (If I recall correctly, most of it was created manually which leaves much room for error)

Your remarks and proposed changes are all valid, except for `known_splices`
Its implementation is arguably a bit hacky:
https://github.com/nf-core/methylseq/blob/031be378eba5e9706642d514494013d9352011ec/main.nf#L121

Essentially, the pipeline currently expects it to be either `false` or a `String`

**Comment by tmuylder** [comment]
Hi @phue ! 
No worries, happy that my work is not irrelevant then 😄 . I've reopened a PR - this time to the `dev` branch so it (hopefully) correctly passes the checks and is able to merge in. That being said, i'll still need to have a look at the `known_splices`.
