### ISSUE TITLE
Where are methylation files generated with methyl_kit option saved?

### ISSUE THREAD

**Issue by tuln128** [nf-core/methylseq#216]
Hello,
I am currently running nf-core/methylseq with bwameth/MethylDackel option to generate methytKit-compartible methylation files. However, I could not find the location of the generated files in the output directory (outDir). Could you please let me know where these files are saved and how can I get them?
Thank you very much in advance.

**Comment by ewels** [comment]
Sorry no-one replied here. Hopefully you found your answer on Slack or in the [docs](https://nf-co.re/methylseq/1.6.1/output#methylation-extraction). It's the same location as the bedGraph files, but called methylKit instead.

Can reopen or take on Slack if anyone is still unclear,
