### ISSUE TITLE
How can I run pipeline using SLURM job submission function

### ISSUE THREAD

**Issue by liuyangzzu** [nf-core/methylseq#224]
Dear methyseq,
I am going to submit each job into a SLURM job to accelerate the running process. Any example of how to use SLURM executor for methyseq? Thank you!

**Comment by phue** [comment]
Dear @liuyangzzu,

Nextflow provides built-in support for various executors, including [Slurm](https://www.nextflow.io/docs/latest/executor.html#slurm)

In the simplest case, you would specify `process.executor = 'slurm'`  via the commandline or a [custom configuration file](https://nf-co.re/usage/configuration#custom-configuration-files). But in most cases, you would also have to specify a slurm partition via the `process.queue` directive for job submission to work correctly.

You might want to have a look https://github.com/nf-core/configs, to see how to create a cluster-specific configuration profile.

**Comment by anijudy** [comment]
Dear phue,

I wonder if you could help me look into my slurm config problem and give me some insights. I was testing the pipeline on my cluster and added the parameter `-c nextflow.config` to the command line. The content of the config file is as follows:
```
(base) [zhaoy@discovery preprocessing2]$ more nextflow.config
executor {
         name   = 'slurm'
         queueSize = 32
}
```

Here is my script:

```
(base) [zhaoy@discovery preprocessing2]$ more run_workflow.batch 
#!/bin/bash
#SBATCH --job-name=MethylSeq                     # Job nname
#SBATCH --error=nextflow_job_%j.err             # Standard output and error log
#SBATCH --output=nextflow_job_%j.out

date
cd /path to my project/preprocessing2
pwd

source activate nextflow

# nextflow run nf-core/methylseq --input samplesheet.csv --outdir <OUTDIR> --genome GRCh37 -profile <docker/singularity/podman/shifter/charliecloud/conda/institute>

nextflow run nf-core/methylseq \
         -resume \
         -profile singularity \
         -c nextflow.config \
         --input samplesheet.csv \
         --outdir results \
         --genome GRCh37 \
         --email xxxxx

date
```
However, I noticed that the nextflow output doesn't report the configFiles being used. The pipeline appears to be running on a single node.

```
(base) [zhaoy@discovery preprocessing2]$ squeue -u zhaoy
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 
           3440681    normal MethylSe    zhaoy  R      20:04      1 e00 
```

Any help is appreciated!

Best,
Yifan
