### ISSUE TITLE
Allow for preindexed custom genomes in dsl2

### ISSUE THREAD

**Issue by TheodoreMarkulin** [nf-core/methylseq#234]
## DSL2 does not allow for using already indexed custom genome

I use a custom variation of GRCh38 that includes control sequences. It takes a while to index the entire genome using `BWAMETH_INDEX` and in practice this should only need to be done once for each custom reference.

It appears that the current dsl2 branch only considers preindexed igenomes references:
https://github.com/nf-core/methylseq/blob/acdc4afccf9fd3dd4150fc4963134300cd5d26d7/subworkflows/local/bwameth.nf#L25-L29

The current branch does this when the `--bwa_meth_index` parameter is passes:

https://github.com/nf-core/methylseq/blob/03972a686bedeb2920803cd575f4d671e9135af0/main.nf#L77-L94

Moving the logic over from the current master branch to the dsl branch would help when doing work with custom genomes.

**Comment by ewels** [comment]
This has been completely refactored in #249 so should now be fixed I think.
