### ISSUE TITLE
Add ability to merge FastQs

### ISSUE THREAD

**Issue by bounlu** [nf-core/methylseq#238]
It is desired to merge files from multiple lanes belonging to the same sample. Often the samples are sequenced in multiple lanes and this indeed speeds up the alignment step, but they need to be merged at the `bam` level.

I think it will be very useful to add this module just like in the `sarek` pipeline:
https://github.com/nf-core/sarek/tree/dev/modules/nf-core/modules/samtools/merge

**Comment by ewels** [comment]
I believe that this is already implemented in the `dsl2` branch and will be included in the next release.

**Comment by bounlu** [comment]
I don't see it in `dsl2` branch yet:
https://github.com/nf-core/methylseq/tree/dsl2/modules/nf-core/modules/samtools

**Comment by ewels** [comment]
You're right, apologies. I know we've talked about adding it previously so it's definitely on the roadmap.

Note that we [usually](https://github.com/nf-core/rnaseq/blob/89bf536ce4faa98b4d50a8ec0a0343780bc62e0a/workflows/rnaseq.nf#L213-L222) just use `cat` rather than `samtools` in other pipelines: https://nf-co.re/modules/cat_fastq

**Comment by ewels** [comment]
Another example from the rnaseq pipeline [here](https://github.com/nf-core/rnaseq/blob/e049f51f0214b2aef7624b9dd496a404a7c34d14/workflows/rnaseq.nf#L189-L222).

**Comment by ewels** [comment]
NB: Neither of these pipelines have the same `check_samplesheet.py` script in their `bin` directories ⚠️ so need to check channel structure etc. (and `_T{n}` suffix trimming)

**Comment by ewels** [comment]
NB: The documentation actually says that you can already do this 🙈 but it's not true.. https://nf-co.re/methylseq/dev/usage#multiple-runs-of-the-same-sample

So we really need to implement this ASAP.

**Comment by SpikyClip** [comment]
Should these be merged at the fastQ level after `INPUT_CHECK` using `CAT_FASTQ` (like the rnaseq pipeline) or should we merge it at the `.bam` level after `ALIGNER` using `SAMTOOLS_MERGE` if alignment is faster before combining them?

**Comment by ewels** [comment]
Done in https://github.com/nf-core/methylseq/pull/272

**Comment by ewels** [comment]
Yes, the PR that was [merged](https://github.com/nf-core/methylseq/commit/c58864ba5e989a9d4c449aaf136e10b8cb63e9b5) has been present in v2.2.0 onwards 👍🏻
