### ISSUE TITLE
(DSL2) Pipeline fails when given a preindexed bwameth index

### ISSUE THREAD

**Issue by TheodoreMarkulin** [nf-core/methylseq#239]
## Description of the bug

Pipeline fails when given a preindexed bwameth index. This is due to the Collect Software Versions step at the end of the `bwameth.nf` script. When provided an index, instead of allowing the pipeline to index the fasta, the version information is not available.

https://github.com/nf-core/methylseq/blob/9f966f910b76d9669750d21a0762900870eb45d9/subworkflows/local/bwameth.nf#L119-L127

## Steps to reproduce

Steps to reproduce the behaviour:

1. Create a bwameth index
2. Add this index to genomes availible to use.
3. Run pipeline with preindexed bwameth assets

## Nextflow Installation

21.10.6

## Container engine

- Engine: AWS Batch+Docker

**Comment by ewels** [comment]
Should be fixed in https://github.com/nf-core/methylseq/pull/249 I think.
