### ISSUE TITLE
Bismark input params for `--multicore` are not used

### ISSUE THREAD

**Issue by bounlu** [nf-core/methylseq#264]
I see there are below 2 parameters in the `nextflow.config` file:

```
bismark_align_cpu_per_multicore
bismark_align_mem_per_multicore
```

However, I don't see where these parameters are ever used in the code.

Ideally Bismark processes should use these parameters as `--multicore` or `-p NTHREADS`.

**Comment by ewels** [comment]
Right, well spotted again - these are legacy options and should be removed.

Multi-core usage is now included in the module [here](https://github.com/nf-core/modules/blob/e84cc8f07607ad7970db9b6cf79b815b78d9cacd/modules/nf-core/bismark/align/main.nf#L30-L40):

```nextflow
    // Try to assign sensible bismark --multicore if not already set
    if(!args.contains('--multicore') && task.cpus){

        // Numbers based on recommendation by Felix for a typical mouse genome
        def ccore = 1
        def cpu_per_multicore = 3
        def mem_per_multicore = (13.GB).toBytes()
        if(args.contains('--non_directional')){
            cpu_per_multicore = 5
            mem_per_multicore = (18.GB).toBytes()
        }
```

I went back and forth on this code a lot in the PR (https://github.com/nf-core/modules/pull/1036)  but in the end decided for this approach.

- Multi-core usage is automatically set based on the Nextflow config
- If the pipeline user wants to override this, then it can be done by overwriting `ext.args`  for this module and specifying `--multicore` there (if it's found in the args, the automatic setting is not applied).

Hopefully this makes sense!

Phil
