### ISSUE TITLE
`--genome` in bwameth and bismark DOESN’T work in v2.1.0

### ISSUE THREAD

**Issue by PanZiwei** [nf-core/methylseq#274]
### Description of the bug

`--genome` DOESN’T work in v2.1.0 for bwameth with the error `The AWS Access Key Id you provided does not exist in our records`. 

`awscli` is installed in the conda environment. I tried to follow https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-key-error/ but no idea how to solve the problem. 

```
Reference genome options
  genome         : GRCh38
  fasta          : s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
------------------------------------------------------
The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: P56RQPNJ5VW2AWNP; S3 Extended Request ID: ZfHnYaxkhfnE/7rNy9/x7wvAYdm2ygKpoQ2G2NM9NNRmh3R31K3Kcs/gRgFBcrvtvjzOSkkzfS4=; Proxy: null)

 -- Check script '/home/c-panz/.nextflow/assets/nf-core/methylseq/./workflows/methylseq.nf' at line: 14 or see '.nextflow.log' file for more details
```

### Command used and terminal output

```console
nextflow run nf-core/methylseq \
-r 2.1.0 \
-profile singularity \
--input $input_dir/sample.csv \
--outdir $output_dir \
--aligner bwameth \
--genome GRCh38
```

### Relevant files

[nextflow_methylseq_GRCh38_bwameth_iGenome.log](https://github.com/nf-core/methylseq/files/10099697/nextflow_methylseq_GRCh38_bwameth_iGenome.log)

### System information

Nextflow version: 21.10.3
Executor: slurm
Container engine: Singularity
OS:CentOS Linux
Version of nf-core/methylseq: 2.1.0

**Comment by ewels** [comment]
This is a problem with AWS authentication, not the pipeline. Let's continue the discussion in Slack 👍🏻
