### ISSUE TITLE
Get to the bottom of index tests

### ISSUE THREAD

**Issue by Emiller88** [nf-core/methylseq#278]
Write tests that aren't dependent on each other. 

https://nfcore.slack.com/archives/CP3RJSMF0/p1669669585086889

We might need to use specific output directories(`$outDir/bwameth` for example) for each test.

**Comment by ewels** [comment]
Do you consider this fixed now @Emiller88 ? Or is this more about decoupling the tests rather than fixing output directory paths?

**Comment by Emiller88** [comment]
More about decoupling them.

I'm not sure if they're working properly right now, but as long as we don't dig into it's Schrodinger's test.
