### ISSUE TITLE
`samtools sort` overwrites

### ISSUE THREAD

**Issue by bounlu** [nf-core/methylseq#328]
I want to extract **deduplicated and sorted** bam file from the pipeline by using the `Bismark` aligner.

When I use `--save_align_intermeds` flag, `SAMTOOLS_SORT` module writes the sorted bam file to the output directory as per this [config](https://github.com/nf-core/methylseq/blob/81f989c93e866a9b0bd0d9584e077b9b8f78affe/conf/modules.config#LL319C1-L335C6):
```
    withName: SAMTOOLS_SORT {
        ext.prefix = { "${meta.id}.sorted" }
        publishDir = [
            [
                path: { "${params.outdir}/${params.aligner}/deduplicated/" },
                mode: params.publish_dir_mode,
                pattern: "*markdup*.bam",
                enabled: params.save_align_intermeds
            ],
            [
                path: { "${params.outdir}/${params.aligner}/alignments/" },
                mode: params.publish_dir_mode,
                pattern: "*.bam",
                enabled: params.save_align_intermeds
            ]
        ]
    }
```

However, `SAMTOOLS_SORT` is used twice with alias in the `BISMARK` [workflow](https://github.com/nf-core/methylseq/blob/81f989c93e866a9b0bd0d9584e077b9b8f78affe/subworkflows/local/bismark.nf#LL5C1-L6C104), one is before and one is after deduplication. The sorted file before deduplication is saved, then the sorted file after deduplication is overwritten. This is because both files use identical filename after sorting due to the same [prefix](https://github.com/nf-core/methylseq/blob/81f989c93e866a9b0bd0d9584e077b9b8f78affe/modules/nf-core/samtools/sort/main.nf#LL22C1-L33C13). This redundancy should be avoided by adding **.deduplicated.sorted.** for the latter.

Moreover, the overwritten file is written to the wrong folder **/alignments/** instead of **/deduplicated/**.

**Comment by sateeshperi** [comment]
hey @bounlu Thanks for reporting this. I just put in some fixes based on your suggestion to the linked branch 

If you could give it a look and lmk if the samtools sort is as expected now 🙏
