### ISSUE TITLE
methylseq is requesting very high compute resources I don't have.

### ISSUE THREAD

**Issue by sahuno** [nf-core/methylseq#332]
### Description of the bug

I'm not sure this is a bug per se.

but I'm running methyl-Seq on HPC cluster. the job has been pending for ~24hrs. it seems  nexflow methyl-Seq is requesting for resources not available on HPC like mem>72 on a single host and 12 cpus. I set minimal compute resource in config file but I'm not able to override the default  methyl-Seq  compute configs. 
I created `nextflow.config`  file in working directory and specifically passed an `custom.config` with `-c` option when lunching `nextflow`

Que - could you please have a look at my config files? or suggest what i can do to make job run successfully?
Thank you in advance for your help!!!!

```
executor {
  name = "lsf"
  queueSize = 25 // no more than 25 HPC jobs running at a time
  queue = 'general'
  cpus = 10
  memory = '24 GB'
  time = '4h'
}

singularity {
  enabled = true
  autoMounts = true
}
```

### Command used and terminal output

```console
`nextflow run nf-core/methylseq --input spectrum_methylation_fastq_sample_sheet.csv --outdir test_run --genome GRCh38 -profile singularity`

`#command 2: with config`
`nextflow run nf-core/methylseq --input spectrum_methylation_fastq_sample_sheet.csv --outdir test_run --genome GRCh38 -profile singularity -c custom.config`
```

### Relevant files

[nextflow.log.zip](https://github.com/nf-core/methylseq/files/12194362/nextflow.log.zip)

### System information

Nextflow version (23.04.1.5866)
Hardware (HPC)
Executor (lsf)
Container engine: (Singularity)
OS (CentOS Linux)
Version of nf-core/methylseq (default)

**Comment by f6v** [comment]
Hi @sahuno don't know if you've figured it out yet, but I don't think it's a bug. I was also confused about it before. 
Check out the config https://github.com/nf-core/methylseq/blob/master/conf/base.config
Processes have these labels like `process_low` or `process_high` which guide resource allocation. What you could try is to add following to custom config (just an example):

```
process {
  withLabel:process_high {
        cpus   = 6
        memory  32.GB
    }
}
```
This could help with your cluster to actually accept the jobs. But whether all the tools can run with such a reduced memory or number of CPUs is something I can't comment on.

Hope this helps!

**Comment by sahuno** [comment]
Dear @f6v
thank you for the comment. i used your advice to create `nextflow.config` file in the working directory with minimal resources and seem to running.

best
-S
