### ISSUE TITLE
Pipeline unable to recognise samples processed across multiple lanes

### ISSUE THREAD

**Issue by jma1991** [nf-core/methylseq#351]
### Description of the bug

I've identified a potential issue in the recent pipeline release (v2.5.0). It seems the groupTuple command is executed twice during the input channel creation and branching of FASTQ files. As a result, the pipeline is unable to recognise samples processed across multiple lanes, due to an additional layer of file nesting. See here: https://github.com/nf-core/methylseq/blob/66c6138322ec5cc87738219e24d65240299dcc10/workflows/methylseq.nf#L98-L105

**Comment by wkang0** [comment]
This is bug in the instruction instead of in the code. To make one sample in different lanes, the sample sheet should look like this: 

sample1_REP1,fq1.gz,fq2.gz
sample1_REP2,fq11,ga,fq12.gz

**Comment by sateeshperi** [comment]
fixed in `2.7.1`. please let us know if any issues. Thank you!
