### ISSUE TITLE
Add bwameth test config

### ISSUE THREAD

**Issue by scoughlan2** [nf-core/methylseq#364]
### Description of feature

[test](https://github.com/nf-core/methylseq/blob/2.5.0/conf/test.config) and [test_full](https://github.com/nf-core/methylseq/blob/2.5.0/conf/test_full.config) configs only test the bismark workflow but not the bwameth subworkflow which means that breaking changes to that workflow can potentially go unnoticed. I am proposing adding a separate test config for the bwameth subworkflow to ensure that it can also be easily tested.

**Comment by sateeshperi** [comment]
Hello, I wanted to point out that we do in fact **nf-test** for all the three different aligners:
 [bowtie2(default)](https://github.com/nf-core/methylseq/blob/d447efa1a2ebb6f5c1d0d5746ed6efd8b30647f7/tests/pipeline/bismark/main.nf.test#L12)
 [hisat2](https://github.com/nf-core/methylseq/blob/d447efa1a2ebb6f5c1d0d5746ed6efd8b30647f7/tests/pipeline/bismark_hisat/main.nf.test#L12)
 [bwameth](https://github.com/nf-core/methylseq/blob/d447efa1a2ebb6f5c1d0d5746ed6efd8b30647f7/tests/pipeline/bwameth/main.nf.test#L12)
 
 you can run any of these tests by their tags as `nf-test test --tag bwameth --profile docker`
 
 The github CI is designed to run all these tests upon changes and verifies against previously recorded snapshot containing the md5sum of files and existence checks.
 
 As it is there is no need for a different test config as the aligner can be specified via the CLI
 
 Let me know if this addresses your concern for any changes to the bwameth workflow going un-noticed.

**Comment by scoughlan2** [comment]
Thank you for explaining this. Yes this does address my concerns!

**Comment by scoughlan2** [comment]
Closing
