### ISSUE TITLE
Scatter CI improvements

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/methylseq#366]
https://github.com/nf-core/methylseq/pull/350#discussion_r1434869399

```[tasklist]
### Tasks
- [ ] Cache Nextflow
- [ ] Clean up Job names
- [ ] Better reporting
```

**Comment by sateeshperi** [comment]
think we can close this issue now that we have nf-test shard.. agree @edmundmiller ?

**Comment by sateeshperi** [comment]
yup on the #414 branch
