### ISSUE TITLE
samplesheet input is not detecting entire values in sample column 

### ISSUE THREAD

**Issue by wvictor14** [nf-core/methylseq#378]
### Description of the bug

when (a certain number of?) underscores are used in sample column, sometimes only a substring of the entire value is read in, rather than the whole value.

E.g. BATCH_DATE_SAMPLE is read in as BATCH_DATE in the following example. The impact is that when the read-in partial value is not unique , the pipeline will erroneously treat multiple (unique) rows as replicates.

See screenshots of an example samplesheet and running pipeline for example

![image (1)](https://github.com/nf-core/methylseq/assets/22013187/64b81776-b63f-4218-919f-8273ea3a6d4e)
![image](https://github.com/nf-core/methylseq/assets/22013187/9733674a-33d8-4515-9657-b525d15a3c80)

### System information

version methylseq 2.6.0
_No response_

**Comment by ewels** [comment]
I suspect that this is the offending code:

https://github.com/nf-core/methylseq/blob/54f823e102ef3d04077cc091a5ae435519f9923a/workflows/methylseq.nf#L101-L103

I'm not 100% if this is a bug or a feature. If a feature then it should have better docs.

**Comment by ewels** [comment]
I think that this issue is essentially the inverse of https://github.com/nf-core/methylseq/issues/351 (here it's happening by accident, there it was the desired behaviour).

**Comment by flerpan01** [comment]
I'm so happy I found this issue, was pulling my hair the whole day thinking my code was wrong. Quickfix: changed the underscore to a dot in my `samplesheet.csv` (F0_1 -> F0.1)

**Comment by CathyXD** [comment]
I've encountered the same issue that the sample name inputs were uncompleted causing later errors. My sequencing was paired-end with 4 lane per sample, so may also have the problem mentioned in  #381 . Could anyone provide an updated workable samplesheet.csv example? Really confused now.

**Comment by AdrijaK** [comment]
>  Could anyone provide an updated workable samplesheet.csv example? Really confused now.

If you add a bogus thing for the last underscore (like suffix _1, _2, _3, _4) to each sample name, they will not be concatenated. Similar thing works for nf-core/chipseq pipeline where everything before the last underscore is used to infer group names.

**Comment by imdanique** [comment]
Thank you!! I've spent a week trying to figure out why the pipeline is strangely concatenating my input fastqs. Could you please add this info regarding naming conventions to README or fix the code?

**Comment by sateeshperi** [comment]
fixed in `2.7.1`. plz report back if any issues. Thank you!
