### ISSUE TITLE
Add gemBS option

### ISSUE THREAD

**Issue by seynard** [nf-core/methylseq#387]
### Description of feature

Hi, I really like using the nf-core MethylSeq but recently we've been wanting to test gemBS to analyse our RRBS data. We are wondering if this tool could be added to the pipeline as an alternative to Bismark or BWAMeth? 
Thanks in advance for your help.

**Comment by sateeshperi** [comment]
hi @seynard could you provide any links to gemBS and why you think it will be a good addition to methylseq ?

**Comment by seynard** [comment]
Hi @sateeshperi, actually I'm not sure gemBS would be the best addition, maybe BISCUIT could also be one, we are working on finding the best tool for our purpose but the idea would be to have, in parallel of the methylation calling also the variant calling from bisulfite sequencing data and as these tools do both they could be nice additions to the general pipeline. We are in the process of testing them and seeing if they answer well our purpose.

**Comment by sateeshperi** [comment]
I have biscuit on my roadmap. Let me know if you want to work together to integrate it.

**Comment by seynard** [comment]
Dear Sateesh, super that it's already on your road map, we also found this fork that have already developed it https://github.com/ekushele/methylseq but a colleague (Rémi Séraphin) and I would definitely be happy to contribute to that so let us know how we can arrange ourselves to help out :)
