### ISSUE TITLE
Latest template merge completely broke dev branch (on AWS + Fusion)

### ISSUE THREAD

**Issue by FelixKrueger** [nf-core/methylseq#392]
### Description of the bug

I am trying to launch a methylseq run using the latest `dev` branch where some (but not a all) samples require merging of technical replicates before launching. If I understand it correctly, the latest template changes were merged into dev [earlier this month](https://github.com/nf-core/methylseq/commit/ee3a02ca2880fa86f688b428a9c01aacefce34d2), but something seems to have gone awry:

Within seconds of launching the run, I observe the following errors:
1. The samples are not getting merged, despite technical replicates having identical IDs (which no longer get truncated by 1 element, which is good!)
2. Trim Galore fails straight away as the system tries to create the same symbolic link several times (details below)
3. As one of the first processes, `bismark2summary` is run, and obviously fails...
<img width="809" alt="Screenshot 2024-03-27 at 11 15 21" src="https://github.com/nf-core/methylseq/assets/5870509/04cb3cac-6576-4545-9c18-aed7d9f6ab03">

Obviously, the `ln -s` command attempts to use the very same filename 6 times over, which doesn't work. But something also screwed up the entire workflow logic, i.e. not starting with merging, and instead running post-run QC right at the start.

Here is an example samplesheet:

```
sample,fastq_1,fastq_2,genome
GSM7506206_P3_plus_12_32F_Smith_C_Klf4,s3://filebucket/SRR24994983_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,,
GSM7506206_P3_plus_12_32F_Smith_C_Klf4,s3://filebucket/SRR24994984_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,,
GSM7506206_P3_plus_12_32F_Smith_C_Klf4,s3://filebucket/SRR24994985_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,,
GSM7506206_P3_plus_12_32F_Smith_C_Klf4,s3://filebucket/SRR24994986_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,,
GSM7506206_P3_plus_12_32F_Smith_C_Klf4,s3://filebucket/SRR24994987_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,,
GSM7506206_P3_plus_12_32F_Smith_C_Klf4,s3://filebucket/SRR24994988_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,,
GSM7431885_NB18_32F_TNTtoKSR_553_rep1,s3://filebucket/SRR24757836_GSM7431885_NB18_32F_TNTtoKSR_553_rep1_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,s3://filebucket/SRR24757836_GSM7431885_NB18_32F_TNTtoKSR_553_rep1_Homo_sapiens_Bisulfite-Seq_R2.fastq.gz,
GSM7431885_NB18_32F_TNTtoKSR_553_rep1,s3://filebucket/SRR24757837_GSM7431885_NB18_32F_TNTtoKSR_553_rep1_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz,s3://filebucket/SRR24757837_GSM7431885_NB18_32F_TNTtoKSR_553_rep1_Homo_sapiens_Bisulfite-Seq_R2.fastq.gz,
```

### Command used and terminal output

```console
This is the command it attempts to run:

Command

[ ! -f  GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz ] && ln -s SRR24994983_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz SRR24994984_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz SRR24994985_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz SRR24994986_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz SRR24994987_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz SRR24994988_GSM7506206_P3_plus_12_32F_Smith_C_Klf4_Homo_sapiens_Bisulfite-Seq_R1.fastq.gz GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz
trim_galore \
    --fastqc \
    --cores 8 \
    --gzip \
    GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz


Terminal output of Trim Galore process:
ln: GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz: File exists
ln: GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz: File exists
ln: GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz: File exists
ln: GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz: File exists
ln: GSM7506206_P3_plus_12_32F_Smith_C_Klf4.fastq.gz: File exists
11:11AM INF shutdown filesystem start
11:11AM INF shutdown filesystem done
```

### System information

<img width="1215" alt="Screenshot 2024-03-27 at 11 06 51" src="https://github.com/nf-core/methylseq/assets/5870509/9afb7faf-2259-4a63-9837-3b0fd86869d6">

I am running this on Seqera platform on AWS, using Fusion. Nextflow v23.10.1 build 5891. nf-core/methylseq version: `dev`

**Comment by edmundmiller** [comment]
Have you tried simplifying the names to just `GSM7431885` and `GSM7506206`

The sample name doesn't have to match the original input, you can name it something more descriptive than an ID as well.

**Comment by FelixKrueger** [comment]
Simplifying the name has no effect (other than a different file name...):
<img width="894" alt="Screenshot 2024-03-28 at 11 02 08" src="https://github.com/nf-core/methylseq/assets/5870509/cf4ce893-42fb-439e-a12f-3377b9f18a87">

```
ln: GSM7506206.fastq.gz: File exists
ln: GSM7506206.fastq.gz: File exists
ln: GSM7506206.fastq.gz: File exists
ln: GSM7506206.fastq.gz: File exists
ln: GSM7506206.fastq.gz: File exists
```

**Comment by edmundmiller** [comment]
> using Fusion

I have a feeling this might be it, with the soft links for whatever weird reason.

Two new experiments:
1. Can you run the methylseq test profile in the environment?
2. Can you run the rnaseq test profile in the environment? (It has trimgalore)
3. If the above two work, what about a rnaseq test full?

Also, any previous versions confirmed? Because the trimgalore module hasn't been updated in 11 months.
