### ISSUE TITLE
Schematic for the methylseq pipeline

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [nf-core/methylseq#395]
### Description of feature

I know there is a [standard practice](https://nf-co.re/docs/contributing/design_guidelines) for making the schematics for the different nf-core pipelines. I just wanted to know the status of this pipeline's diagram.

Is anyone working on it? If not, I'd be glad to make it.

**Comment by sateeshperi** [comment]
@Shaun-Regenbaum would you still be interested in making a metro map for methylseq ?

**Comment by Shaun-Regenbaum** [comment]
I would be, I'm traveling at the moment but in a few weeks?

**Comment by sateeshperi** [comment]
We are planning for a release in next few weeks. would be cool to have a metro map for the release if we can. Thanks a lot! much appreciated.

**Comment by sateeshperi** [comment]
plz reach out on the slack channel if you need any help

**Comment by sateeshperi** [comment]
related #383 

@matrulda if you could help in any way for creating the metro maps, that would be much appreciated!

**Comment by sateeshperi** [comment]
hey @Shaun-Regenbaum @matrulda 

any chance you got to work on the metro map ?

**Comment by Shaun-Regenbaum** [comment]
Yah, I have a rough draft:
![Image](https://github.com/user-attachments/assets/0929d3ab-eaf5-4b16-ba79-aa095fb2d57a)
How does this look?

**Comment by Shaun-Regenbaum** [comment]
Let me know if there are any changes, otherwise I can create the appropriate svg and png files.

**Comment by sateeshperi** [comment]
minor- `Qualimap` is spelled wrong

but, this is looking real good

looping @ewels @maxulysse @edmundmiller @FelixKrueger for review & suggestions

**Comment by sateeshperi** [comment]
the `bwameth` & `bismark` nodes can be called `Bwameth Align` & `Bismark Align` I think....thoughts ? 

Also we do have `bismark_hisat` option, wonder if that should be represented somehow ?

**Comment by Shaun-Regenbaum** [comment]
I am fine with that, in regards to hisat, if we are going to include three pipelines, we should add it to the steps: ![Image](https://github.com/user-attachments/assets/3ed884e3-1c4c-489e-8b69-fae426658ae3)

Otherwise, if we are treating it as an optional parameter, we should not include it in my opinion. Like if we want to include it we should have some documentation on when you want to use hisat vs bowtie in this context.

**Comment by sateeshperi** [comment]
https://felixkrueger.github.io/Bismark/bismark/alignment/#local-alignments-in-bowtie-2-or-hisat2-mode

guess we can cover some of this in the docs

**Comment by sateeshperi** [comment]
I added you the the methylseq channel in nf-core slack if you don't mind we can carry our conversation there ?

**Comment by sateeshperi** [comment]
Hi could you share the map files in the slack thread after your edits when you get a chance. Thanks a lot!

**Comment by Shaun-Regenbaum** [comment]
For visibility sake (after edits):
![Image](https://github.com/user-attachments/assets/1ff0f3cf-9c39-4d42-a3ee-bc552993ac09)

Figma file:
https://www.figma.com/design/hRVmy685BFWHyC4hblT0fH/MetroMap?node-id=0-1&t=HeddxLQHd8B0GlUD-1

Relevant Slack Thread:
https://nfcore.slack.com/archives/CP3RJSMF0/p1729414417909319

**Comment by Shaun-Regenbaum** [comment]
Going off steps:
Bismark/Bismark_Hisat:
PREPARE_GENOME:BISMARK_GENOMEPREPARATION
METHYLSEQ:CAT_FASTQ
METHYLSEQ:FASTQC
METHYLSEQ:TRIMGALORE
METHYLSEQ:BISMARK:BISMARK_ALIGN
METHYLSEQ:BISMARK:SAMTOOLS_SORT_ALIGNED
METHYLSEQ:BISMARK:BISMARK_DEDUPLICATE
METHYLSEQ:BISMARK:BISMARK_METHYLATIONEXTRACTOR
METHYLSEQ:BISMARK:BISMARK_REPORT
METHYLSEQ:BISMARK:BISMARK_SUMMARY
METHYLSEQ:BISMARK:SAMTOOLS_SORT_DEDUPLICATED
METHYLSEQ:BISMARK:SAMTOOLS_INDEX_DEDUPLICATED
METHYLSEQ:QUALIMAP_BAMQC
METHYLSEQ:PRESEQ_LCEXTRAP
METHYLSEQ:MULTIQC
Bwameth:
PREPARE_GENOME:BWAMETH_INDEX
METHYLSEQ:CAT_FASTQ
METHYLSEQ:FASTQC
METHYLSEQ:TRIMGALORE
METHYLSEQ:BWAMETH:BWAMETH_ALIGN
METHYLSEQ:BWAMETH:SAMTOOLS_SORT
METHYLSEQ:BWAMETH:SAMTOOLS_INDEX_ALIGNMENTS
METHYLSEQ:BWAMETH:SAMTOOLS_FLAGSTAT
METHYLSEQ:BWAMETH:SAMTOOLS_STATS
METHYLSEQ:BWAMETH:PICARD_MARKDUPLICATES
METHYLSEQ:BWAMETH:SAMTOOLS_INDEX_DEDUPLICATED
METHYLSEQ:BWAMETH:METHYLDACKEL_EXTRACT
METHYLSEQ:BWAMETH:METHYLDACKEL_MBIAS
METHYLSEQ:QUALIMAP_BAMQC
METHYLSEQ:PRESEQ_LCEXTRAP
METHYLSEQ:MULTIQC (edited)

**Comment by Shaun-Regenbaum** [comment]
Final update:

![Image](https://github.com/user-attachments/assets/d9e39485-2996-4c70-8c80-f5e07e06d08e)

Addressed in merge #437

**Comment by matrulda** [comment]
> related [#383](https://github.com/nf-core/methylseq/issues/383)
> 
> [@matrulda](https://github.com/matrulda) if you could help in any way for creating the metro maps, that would be much appreciated!

Sorry for not replying earlier! I've been kind of swamped. I think @Shaun-Regenbaum did an excellent job, thank you!
