### ISSUE TITLE
Preseq error

### ISSUE THREAD

**Issue by gevro** [nf-core/methylseq#409]
### Description of the bug

All the preseq jobs are failing with the below error:
PRESEQ_LCEXTRAP (SAMPLE)` terminated with an error exit status (137) -- Error is ignored

There is no further log or output files to figure out why.

### Command used and terminal output

```console
Latest dev branch
```

**Comment by sateeshperi** [comment]
hi @gevro this is not a bug. this failure is expected from this tool though i am not entirely sure what causes this error in the tool. And you can ignore the failure of this step unless absolutely required.

would like to close this issue if not affecting the actual pipeline behavior

**Comment by gevro** [comment]
Ok feel free to close. Where do the preseq results show up then?

**Comment by sateeshperi** [comment]
according to the [config](https://github.com/nf-core/methylseq/blob/fc4f6658c3020afd036129f27f540a3b423fec72/modules/nf-core/preseq/lcextrap/nextflow.config#L6), if the process is successful the results and log should be in `"${params.outdir}/${params.aligner}/preseq"`

**Comment by gevro** [comment]
The output does not show up in preseq. Probably due to the bug. Nextflow thinks the process failed even though it finished successfully based on the logs.
