### ISSUE TITLE
Massive disk usage

### ISSUE THREAD

**Issue by gevro** [nf-core/methylseq#410]
### Description of the bug

Hi,
For ~40x whole-genome bisulfite sequencing x ~20 samples, the pipeline is using > 30 Tb of disk space. This seems too much.

Also, when the pipeline fails for example, and then I restart, it then takes up even more space.

I think the issue is that copies of the large fastq and bam files are made for each step, instead of using symlinks.

Perhaps this is an issue with nextflow in general rather than nf-core, but this is not a feasible way to process genomics data at scale.

### Command used and terminal output

```console
Latest dev version
```

**Comment by sateeshperi** [comment]
hi @gevro bismark align has a `--gzip` option that you can add provide via `ext.args` to reduce the disk space usage of intermediate files.

> Also, when the pipeline fails for example, and then I restart, it then takes up even more space.

That is expected as it is currently a nextflow limitation that you cannot delete old intermediate files until the workflow finishes successfully. Though there is a new beta plugin on experimental cleanup with [nf-boost](https://www.nextflow.io/blog/2024/experimental-cleanup-with-nf-boost.html) that you could look into if interested. 

Let me know if you are good with above explanation.

**Comment by gevro** [comment]
Got it, ok. thanks
