### ISSUE TITLE
Make a where_are_my_files.txt

### ISSUE THREAD

**Issue by ewels** [nf-core/methylseq#42]
In the rnaseq pipeline we save a text file called `where_are_my_files.txt` when the intermediate BAM files etc are not saved to results. Would be good to do that here too.

**Comment by MaxUlysse** [comment]
Not really sure I understand the point of that text file.
Can you elaborate a little more?

**Comment by ewels** [comment]
When intermediate files are not saved, we have empty directories with just logs and no Bam / FastQ files. Then users think that the pipeline hasn't worked and create bug reports. With this we just create a small file explaining this which gets copied into the results directory.

https://github.com/nf-core/rnaseq/blob/master/assets/where_are_my_files.txt
https://github.com/nf-core/rnaseq/blob/44f1525d7adfa3a6afcafdcf7730eca78a1a2511/main.nf#L489-L490

**Comment by MaxUlysse** [comment]
Oh I see!
Good idea
