### ISSUE TITLE
Is the cytosine report (.CpG_report.txt.gz) analyzed from deduplicated data?

### ISSUE THREAD

**Issue by gevro** [nf-core/methylseq#423]
Hi,
Question: Is the cytosine report (.CpG_report.txt.gz) analyzed from deduplicated data?

Seems like it from the code, but wanted to confirm definitively.

Thanks

**Comment by sateeshperi** [comment]
Yes by default it will analyzed from deduplicated bam unless, used with `--skip_dedup` param then it would be the raw aligned bam
