### ISSUE TITLE
Command error: ln: Sample_Name.fastq.gz: File exists

### ISSUE THREAD

**Issue by OliverH96** [nf-core/methylseq#425]
I'm running methylseq v2.6.0 on some RRBS data, but am having some trouble. I've been getting the error:

ERROR ~ Error executing process > 'NFCORE_METHYLSEQ:METHYLSEQ:TRIMGALORE (MBioS_BACD)'
Caused by:
  Process `NFCORE_METHYLSEQ:METHYLSEQ:TRIMGALORE (MBioS_BACD)` terminated with an error exit status (1)
Command executed:
  [ ! -f  MBioS_BACD.fastq.gz ] && ln -s L10767_EKDL240033743-1A_22FYT3LT4_L2_1.fq.gz L10767_EKDL240033743-1A_22FYT3LT4_L2_2.fq.gz MBioS_BACD.fastq.gz
  trim_galore \
      --fastqc --rrbs \
      --cores 8 \
      --gzip \
      MBioS_BACD.fastq.gz
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_METHYLSEQ:METHYLSEQ:TRIMGALORE":
      trimgalore: $(echo $(trim_galore --version 2>&1) | sed 's/^.*version //; s/Last.*$//')
      cutadapt: $(cutadapt --version)
  END_VERSIONS
Command exit status:
  1
Command output:
  (empty)
Command error:
  ln: MBioS_BACD.fastq.gz: File exists
Work dir:
  /gpfs01/home/sbzoh/F3_Liver/work/c4/02282c9975862e1425406903f4193c
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

I'm not sure why the file existing would give an error, as this should surely stop the symbolic link to the 2 input files being formed and trim galore should continue with the merged  MBioS_BACD.fastq.gz file?

**Comment by sateeshperi** [comment]
hi @OliverH96 could you kindly test with the current `dev` branch and see if that works for you

**Comment by sateeshperi** [comment]
hi @OliverH96 kindly test with the new release 3.0.0 and report back if you see the issue again. 

Closing this for now
