### ISSUE TITLE
Hard-coded settings for Bismark

### ISSUE THREAD

**Issue by cjfields** [nf-core/methylseq#43]
I noticed two hard-coded settings for bismark that are only for paired-end calls

https://github.com/nf-core/methylseq/blob/62d30e1d06d194047a372be60e4755fd8d0e9281/main.nf#L511-L512

Should these be moved into parameters?

**Comment by ewels** [comment]
Hi @cjfields,

We certainly could - however, because the pipeline runs trimming with Trim Galore prior to alignment, I haven't felt the need to before. The number of bases to trim is configurable. Is there a context where it would make sense to alter both, or one and not the other?

Phil

**Comment by cjfields** [comment]
We've had instances where we would like to rerun the workflow but tweak the bismark methylation extraction step w/o having to rerun the full pipeline.  

In particular I noticed a technology-specific methylation bias from RRBS data at the 5' end of the sequence (a single base) and wanted to remove it to prevent false-positive calls; this is for UMI-based deduplication.  The data are single-end reads (and so I needed to introduce the parameters for this purpose), but I happened to notice the hard-coded options in the paired-end step.

We're currently doing this on a fork, with the UMI code in a branch:

https://github.com/HPCBio/methylseq/blob/0a1aafac534449bd2591a15752b0f1631c7e6c2a/main.nf#L644

**Comment by ewels** [comment]
> We've had instances where we would like to rerun the workflow but tweak the bismark methylation extraction step w/o having to rerun the full pipeline.

Yup. that's a good reason! Can certainly add it, very easy to do.

Separately, NuGEN UMI support would be nice to add. It's quite a common kit type, there's a good chance that we'll also want to run with this in the future too. Would be great if we can merge that into the main release some time :)

**Comment by cjfields** [comment]
> Separately, NuGEN UMI support would be nice to add. It's quite a common kit type, there's a good chance that we'll also want to run with this in the future too. Would be great if we can merge that into the main release some time :)

That's the long-term goal, as well as adding UIUC support for running this on our various cluster resources :)

**Comment by ewels** [comment]
Sounds great!

Would be good to add you guys to the list of contributors too in that case 😉 http://nf-co.re/about - just make a PR adding yourself to https://github.com/nf-core/nf-co.re/blob/master/nf-core-contributors.yaml along with a colour and white logo in SVG (I can help with these if you want).

**Comment by ewels** [comment]
Just had a look and it seems that these options are now set via parameters:

https://github.com/nf-core/methylseq/blob/44b80aa2bf6e8f11e23d506227bbd7293c108cb1/conf/modules.config#L214-L215

They're still set to `2` by default in `nextflow.config`:

https://github.com/nf-core/methylseq/blob/44b80aa2bf6e8f11e23d506227bbd7293c108cb1/nextflow.config#L66-L67

..but they're params and in the schema so should now be very easy to adjust and customise.

So I think that this issue can be closed as completed ✨
