### ISSUE TITLE
specify available memory to Picard

### ISSUE THREAD

**Issue by zchatt** [nf-core/methylseq#45]
Hello,

Thank you for this fantastic workflow. I have found it extremely useful. 

I had an issue when running larger `.fastq` files (64Gb each R1 and R2) through the bwa-mem workflow in which java would throw an error:
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
```
After some reading I found this was related to the java heap space. 

I was able to get around this by increasing the heap space within the `main.nf` file (prior to `markDuplicate` command) using the following command `export _JAVA_OPTIONS="-Xmx200g"`.

Thought I would leave this here in case others had the same issue. This is a solution, not sure if it is the best. 

Cheers,

Zac

**Comment by ewels** [comment]
Hi @zchatt,

Thanks for your detailed issue and fix! Yes, I think we should be specifying the memory available for Picard. We're already [doing this](https://github.com/nf-core/rnaseq/blob/1cd5ab733a35727b01370de2ae8462d65f57fbb9/main.nf#L849-L857) in other nf-core pipelines, so it should be a simple fix:

```nextflow
    script:
    if( !task.memory ){
        log.info "[Picard MarkDuplicates] Available memory not known - defaulting to 3GB. Specify process memory requirements to change this."
        avail_mem = 3
    } else {
        avail_mem = task.memory.toGiga()
    }
    """
    picard -Xmx${avail_mem}g MarkDuplicates \\
```

Phil

**Comment by ewels** [comment]
Hi @zchatt,

I've just made this change and merged into the `dev` branch. You can use this code by specifying `-r dev` when running nextflow. Hopefully this will solve your problem.

It'll be properly released when the next version of the pipeline goes out.

Let us know if you hit any problems and thanks for reporting this!

Phil

**Comment by zchatt** [comment]
Fantastic. I will give it a go now.

Cheers,

Z
