### ISSUE TITLE
Failure parsing sample sheet, FASTA is null

### ISSUE THREAD

**Issue by johncthomas** [nf-core/methylseq#454]
### Description of the bug

I get the error

```
ERROR ~ Cannot invoke method endsWith() on null object                                                                     
                                                                                                                           
 -- Check script '/home/username/.nextflow/assets/nf-core/methylseq/./subworkflows/local/prepare_genome/main.nf' at line: 26...
```

Looking at prepare_genome/main.nf it's because `fasta` is null. I suspect it shouldn't be trying to prepare a genome at all because I'm supplying `--bismark_index DIR`, but I'm not sure.

I don't get this error when running with 2.6.0. Didn't try 2.7.0.

### Command used and terminal output

```console
nextflow run nf-core/methylseq \
	--input nf_methylseq_samplesheet.2.csv \
	-w ~/project/tmp/methylseq/work/20241111-canary \
	--outdir /rds/project/rds-nutgKVmnlpI/CM1014_Canary/data/methylseq/2024-11-11 \
	--save_reference \
	--non_directional \
	--num_mismatches 0 \
	--bismark_index /rds/project/rds-nutgKVmnlpI/Ref/GRCh38/ \
	--aligner bismark \
	 -c /rds/project/rds-nutgKVmnlpI/tools/nfcore_configs/cambridge_icelake_himem.config


With a sample sheet that looks like 


sample,fastq_1,fastq_2
name,fastq.r_1.fq.gz,fastq.r_2.fq.gz


or 


sample,fastq_1,fastq_2,genome
name,fastq.r_1.fq.gz,fastq.r_2.fq.gz,
```

### System information

nf-core/methylseq: 2.7.1
nextflow: 24.10.0

**Comment by sateeshperi** [comment]
@johncthomas You will need to provide the `--fasta` file along with the bismark index. This change was introduced in `2.7.1` where to avoid nested symlinks in the index folder, you will now have to provide the fasta file which is later symlinked into the index folder. Do try providing fasta file and plz report back if any issues

**Comment by johncthomas** [comment]
Ah fair enough! Thanks for the fast response. Yes it does work when given the fasta. 

Catching this earlier and giving a clearer error message would be nice, like "--fasta must also be given when an index is supplied".

**Comment by sateeshperi** [comment]
good point! I will see if I can add a warn message. will update back
