### ISSUE TITLE
Nondeterministic execution of bismark_report task

### ISSUE THREAD

**Issue by pditommaso** [nf-core/methylseq#48]
Trying this pipeline I've noticed that the input definition for the process `bismark_report` is seriously flawed: 

```nextflow
input:
    file bismark_align_log_1
    file bismark_dedup_log_1
    file bismark_splitting_report_1
    file bismark_mbias_1
```

It gets inputs from: 
  * `bismark_align`
  * `bismark_deduplicate` 
  * `bismark_methXtract` 
  * `bismark_methXtract` 

Each of the above processes have an nondeterministic execution order (due to parallel execution) and there's no guarantees that the inputs are received in the same order for different processes. This means that `bismark_report` is receiving a messed input composition. 

The output should include a read name component (instead of extracting it from the file name!) and use it to recompose the input channel for the `bismark_report` using the `join` operator.

**Comment by ewels** [comment]
Yes, good spot - this is a bad bug. Thanks @pditommaso, I'll fix when I get back from holiday.

**Comment by ewels** [comment]
https://github.com/nf-core/methylseq/blob/93600734bc7a1c1a12a3848b4429425ee3aee79c/main.nf#L528-L536

**Comment by pditommaso** [comment]
Enjoy your holidays!
