### ISSUE TITLE
Error when running `2.7.0` and `2.7.1`

### ISSUE THREAD

**Issue by dcarrillox** [nf-core/methylseq#482]
### Description of the bug

Hi, 

I tried to run both `2.7.0` and `2.7.1` versions with my own data but without much success. When running the tests, they throw the same error (below). Tests for the `2.6.0` ran smoothly. Any idea?

Thanks, 
Daniel

### Command used and terminal output

```
$ nextflow run nf-core/methylseq -r 2.7.0 -profile test,singularity --outdir results
Nextflow 24.10.2 is available - Please consider updating your version to it

 N E X T F L O W   ~  version 24.10.0

Launching `https://github.com/nf-core/methylseq` [ecstatic_archimedes] DSL2 - revision: aac172df2c [2.7.0]

ERROR ~ Class definition not found: nextflow/validation/HelpConfig

 -- Check script '.nextflow/assets/nf-core/methylseq/./workflows/methylseq/main.nf' at line: 14 or see '.nextflow.log' file for more details
```

**Comment by sateeshperi** [comment]
hi what is the java version you are using ?

**Comment by sateeshperi** [comment]
could you update your nextflow version to `24.0.2` and try once plz

**Comment by sateeshperi** [comment]
also the error line `nextflow/validation/HelpConfig` points to a possible use of nf-validation which has since been depreciated in favor of nf-schema which is available in `2.7.1`. 

Maybe it has been cached and its trying to use that. Could you remove any previous `.nextflow` folder and also try again if you see the same error

**Comment by sateeshperi** [comment]
hi @dcarrillox any update on above ?

**Comment by sateeshperi** [comment]
hi @dcarrillox a new release is out - v3.0.0. Kindly try with that and report back if you see the same issue.

closing this for now

**Comment by dcarrillox** [comment]
Hi @sateeshperi, sorry for the late reply, too many things on my plate. Release v3.0.0 works like a charm after removing the `.nextlfow` folder. Thank you!
