### ISSUE TITLE
Empty .bedGraph.gz and .bismark.cov.gz files

### ISSUE THREAD

**Issue by geethavenk** [nf-core/methylseq#483]
### Description of the bug

Hi, I am using methylseq and for one of the samples, the .bedGraph.gz and .bismark.cov.gz files are empty. When I checked the .command.err file, I see the following error.
"Failed to open filehandle: Too many open files at /usr/local/bin/bismark2bedGraph line 279, <IN> line 7034081."
I did not have this problem before while processing the samples. 

### Command used and terminal output

```console
nextflow run nf-core/methylseq \
  -r 2.6.0 \
  --input /samplesheets/samplesheet_sample_m.csv \
  --outdir /output/sample_m \
  --unmapped \
  --em_seq \
  --meth_cutoff 1 \
  --bismark_index /ucsc/BismarkIndex/ \
  -c gvenk_mod.config


Output:
Now writing methylation information for file >>CpG_OT_sample_m_1_val_1_bismark_bt2_pe.deduplicated.txt.gz<< to individual files for each chromosome
Failed to open filehandle: Too many open files at /usr/local/bin/bismark2bedGraph line 279, <IN> line 7034081.
Finished BedGraph conversion ...
```

### System information

Nextflow version - 23.10.1
Hardware - HPC

**Comment by sateeshperi** [comment]
TODO: add `--scaffolds` option to docs
https://felixkrueger.github.io/Bismark/options/methylation_extraction/#bedgraph-specific-options

**Comment by sateeshperi** [comment]
@geethavenk Kindly update whether the above param helps with the reported issue

**Comment by sateeshperi** [comment]
Do re-open this issue if it still doesn't work with providing the ext.args
