### ISSUE TITLE
test command wrong in usage.md

### ISSUE THREAD

**Issue by fbnrst** [nf-core/methylseq#501]
I noticed that the test command in `usage.md` is wrong. 
There is a `--input samplesheet.csv` that should not be there:
https://github.com/nf-core/methylseq/blob/4415e90a60faba40ccefd4c847666d28688a86ee/docs/usage.md?plain=1#L178-L182
I believe the correct command is:
```bash
nextflow run nf-core/methylseq \
  --outdir <OUTDIR> \
  --genome GRCh38 \
  -profile test,<docker/singularity/podman/shifter/charliecloud/conda/institute>
```

**Comment by sateeshperi** [comment]
yup.....good catch...thanks for reporting...could you open a PR to dev with the change. Thanks

**Comment by sateeshperi** [comment]
yup good catch......plz open a PR to dev with the change. Thank you
