### ISSUE TITLE
Move the test data into a new repository and set up clones

### ISSUE THREAD

**Issue by ewels** [nf-core/methylseq#6]
Instead of bundling the test data in for every person who ever runs the pipeline, move to a branch of a separate repo and tag a subrepository. Then when developing and testing we can easily clone recursively to get the data, but it won't be fetched for everyone else.

**Comment by sven1103** [comment]
nf-core/test-datasets

**Comment by ewels** [comment]
https://github.com/ewels/test-datasets

**Comment by ewels** [comment]
https://github.com/nf-core/test-datasets

**Comment by ewels** [comment]
Done in #19
