### ISSUE TITLE
implementing bam_merge step for multiple split bam's for a given sample

### ISSUE THREAD

**Issue by sb43** [nf-core/methylseq#71]
Hi Felix,

I have implemented additional step which will merge multiple bams for a sample after alignment.

e.g., SampleA : split_0_R1_fastq.gz, split_0_R2_fastq.gz
        SampleA: split_1_R1_fastq.gz, split_1_R2_fastq.gz
        SampleB: split_0_R1_fastq.gz, split_0_R2_fastq.gz
        SampleB: split_1_R1_fastq.gz, split_1_R2_fastq.gz

Below is snippet to handle this.

   /*
     * STEP 3.2 - merge split bams
     */

     if( params.merge ) {  
        sample_name = params.name
        process merge_bams {
            tag "$name"
            publishDir "${params.outdir}/bismark_alignments", mode: 'copy',
                saveAs: {filename ->
                                    if (filename.indexOf(".merged.bam") > 0) filename
                                    else null
                        }

            input:
            file(bams) from ch_bam_for_merge.collect()

            output:
            set val(sample_name), file("*.merged.bam") into ch_bam_for_bismark_deduplicate

            script:
            """
            samtools merge -n ${sample_name}.merged.bam ${bams}
            """
        }
     }   
     else{
         ch_bam_for_merge_pass.into{ch_bam_for_bismark_deduplicate}
     }

I will share the  forked branch  once did some tidy up.

Thanks,
Shriram

**Comment by ewels** [comment]
Thanks @sb43! I'll close this issue as you have a pull request open now, just to keep all of the discussion in one place.

And although I ping @felixkrueger on Bismark issues, he's not actually involved in maintaining this pipeline _(yet anyway, I've been trying to get them to use nextflow for a while now)._

Phil
