### ISSUE TITLE
Add --methylKit flag to MethylDackel

### ISSUE THREAD

**Issue by bazyliszek** [nf-core/methylseq#75]
Hi, I am trying to use -profile conda on HPC with following code 1) and error 2)
The conda env is downloaded automatically to work/conda and runs first few processes for all samples after which it crashes.  Thanks

1)
```bash
./nextflow run /rds/homes/w/wm/methylseq-1.3/ -resume  -profile conda \
  --reads '/rds/projects/2016/mw/Epi/epidata/170310_D00261_0393_BCAJU6ANXX_8_IL-TP-*{1,2}.fastq.gz' \
  --outdir . \
  --aligner 'bwameth' \
  --fasta '/rds/reference/pa42_assembly_v3.fasta' \
  --zymo --saveTrimmed --saveAlignedIntermediates --unmapped --comprehensive \
  --max_memory 65.GB --memory 30.GB --max_cpus 5 \
```

2) 
Error is following:
```
[warm up] executor > local
[07/4f4158] Cached process > get_software_versions
[27/c34b8e] Cached process > makeFastaIndex (pa42_assembly_v3.fasta)
[89/339d82] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-009)
[41/4dd6bc] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-006)
[6d/7e7171] Cached process > makeBwaMemIndex (pa42_assembly_v3.fasta)
[d9/3467b2] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-003)
[51/7c1f53] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-005)
[b1/542310] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-012)
[f1/c714af] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-008)
[67/13b7cc] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-002)
[87/b332d8] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-001)
[42/77a29f] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-004)
[3a/33df5f] Cached process > fastqc (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-007)
[d5/34d865] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-004)
[d6/009478] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-005)
[69/f3f511] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-012)
[75/175365] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-007)
[dd/0d9c46] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-006)
[82/b801e0] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-008)
[da/8889a9] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-001)
[86/7bf673] Cached process > trim_galore (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-002)
[4f/c3192a] Cached process > bwamem_align (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-008)
ERROR ~ Error executing process > 'samtools_sort_index_flagstat (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-008)'

Caused by:
  Cannot invoke method toBytes() on null object

Source block:
  """
  samtools sort $bam \\
      -m ${task.memory.toBytes() / task.cpus} \\
      -@ ${task.cpus} \\
      -o ${bam.baseName}.sorted.bam
  samtools index ${bam.baseName}.sorted.bam
  samtools flagstat ${bam.baseName}.sorted.bam > ${bam.baseName}_flagstat_report.txt
  samtools stats ${bam.baseName}.sorted.bam > ${bam.baseName}_stats_report.txt
  """

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
[be/e133bb] Submitted process > bwamem_align (170310_D00261_0393_BCAJU6ANXX_8_IL-TP-006)
[nf-core/methylseq] Pipeline Complete
WARN: Killing pending tasks (1)
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
```

**Comment by ewels** [comment]
Hi @bazyliszek,

I think this problem is because you need to use `-profile standard,conda` instead of just `-profile conda`. Without this, you're missing the base configuration.

Note that you're not the first person to be caught out by this and we will remove the need for it in the future (probably the next release). So hopefully for v1.4 `-profile conda` will work fine :)

Let me know if this fixes the problem for you!

Phil

**Comment by bazyliszek** [comment]
Great Phil, that was the problem indeed.  Can I also ask how can we implement the extra parameter in  the -- MethylDackel, that is --methylKit parameter?  
Thanks, Bazyl

**Comment by ewels** [comment]
Great!

Could you clarify the second question please - you mean that you would like to add in a parameter to the MethylDackel command that isn't there currently?

What does it do? Should it always be there or optional only?

**Comment by bazyliszek** [comment]
Yes, to add it as an optional parameter would be great! The --methylKit parameter would produce bed files that are compatible with methylKit R package.  I achieved this by manipulating main.nf file under /rds/homes/w/wm/methylseq-1.3/      line:  MethylDackel extract --methylKit $allcontexts $ignoreFlags $mindepth $fasta $bam   but this is maybe not so elegant?   It would be also great to have importing option to BiSeq at some point.   BiSeq allows the import of Bismark output files so I am not sure if the MethylDackel produce the same format as Bismark?

**Comment by ewels** [comment]
If it's just making an additional output format, assuming that it doesn't add a lot to the run time, I think we can just add that flag for all bwameth runs (instead of making it optional and off by default.).

It looks like BiSeq takes the `bedGraph` output files from Bismark (correct me if I'm wrong). I think that MethylDackel generates the same type of file. Are these not already generated / compatible with BiSeq? What additional functionality would you want here?

**Comment by bazyliszek** [comment]
Additional output format would be nice. It is taking a bit time though, as it is extraction step. I noticed that adding --methylKit parameter will not produce bedgraph files. 

Input for the BiSeq is "bismark.cov.gz" files from Bismark.  Maybe others, @dpryan79 , @KatjaHebestreit have some comments as well?

**Comment by ewels** [comment]
Hi @bazyliszek,

I've just opened a pull request to add a new `--methylKit` command line option to the pipeline (#83). When merged, this functionality will be available using `nextflow run nf-core/methylseq -r dev`, and in the next stable release.

For BiSeq - MethylDackel is already producing `.bedGraph` files which I think should be comparable to the `bismark.cov.gz` files from Bismark. See https://github.com/dpryan79/MethylDackel#single-cytosine-methylation-metrics-extraction :

> `MethylDackel extract` produces a variant of bedGraph that's similar to the "coverage" file produced by Bismark and Bison. 

If there's something else that you need aside from this, let me know.

Phil

**Comment by bazyliszek** [comment]
thanks Phil! I will check and let you know. Bit delayed on testing singularity on TSD (secure cluster in Norway) ... lots of security slows down.

**Comment by ewels** [comment]
Sounds good! I'll close this issue now, but we can reopen it if you find any problems.

Phil
