### ISSUE TITLE
Centralized configs

### ISSUE THREAD

**Issue by apeltzer** [nf-core/methylseq#78]
Need to add this here to the pipeline config to make the release work again:

https://github.com/nf-core/atacseq/blob/master/nextflow.config#L68-L80

**Comment by phue** [comment]
Ah, that's why it stopped working :thinking:

**Comment by apeltzer** [comment]
Unfortunately yes, opened an issue in nf-core/tools and nf-core/configs to make sure this never happens again.... didn't see it yesterday but some project managers had quite some trouble today because of this :-(

**Comment by phue** [comment]
It only affected dev branches of pipelines, after all

**Comment by apeltzer** [comment]
Not only - all that used the master branch :-/ and some were released so these won’t work either ...

**Comment by ewels** [comment]
Now resolved, sorry for breaking stuff 🙇
