### ISSUE TITLE
samtools sort requests too much memory

### ISSUE THREAD

**Issue by sb43** [nf-core/methylseq#81]
All previous process run without error.
I noticed that at each retry number of threads and memory is increased.
Any workaround is accepted.
have you thought of using biobambam2 which seems more efficient.
https://gitlab.com/german.tischler/biobambam2

```
[02/b252cc] Submitted process > qualimap (30jan18_mysample)
[97/8473b0] Submitted process > bismark_methXtract (30jan18_mysample)
[02/b252cc] NOTE: Process `qualimap (30jan18_mysample)` terminated with an error exit status (137) -- Execution is retried (1)
[be/827d8a] Re-submitted process > qualimap (30jan18_mysample)
[be/827d8a] NOTE: Process `qualimap (30jan18_mysample)` terminated with an error exit status (137) -- Execution is retried (2)
[72/1d29bf] Re-submitted process > qualimap (30jan18_mysample)
[72/1d29bf] NOTE: Process `qualimap (30jan18_mysample)` terminated with an error exit status (137) -- Execution is retried (3)
[34/099bd8] Re-submitted process > qualimap (30jan18_mysample)
ERROR ~ Error executing process > 'qualimap (30jan18_mysample)'

Caused by:
  Process `qualimap (30jan18_mysample)` terminated with an error exit status (137)

Command executed:

  samtools sort 30jan18_mysample#1_R1_val_1_bismark_bt2_pe.deduplicated.bam \
      -m 8589934592 \
      -@ 16 \
      -o 30jan18_mysample#1_R1_val_1_bismark_bt2_pe.deduplicated.sorted.bam
  qualimap bamqc  \
      -bam 30jan18_mysample#1_R1_val_1_bismark_bt2_pe.deduplicated.sorted.bam \
      -outdir 30jan18_mysample#1_R1_val_1_bismark_bt2_pe.deduplicated_qualimap \
      --collect-overlap-pairs \
      --java-mem-size=128G \
      -nt 16

Command exit status:
  137

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  .command.sh: line 5:    21 Killed                  samtools sort 30jan18_mysample#1_R1_val_1_bismark_bt2_pe.deduplicated.bam -m 8589934592 -@ 16 -o 30jan18_mysample#1_R1_val_1_bismark_bt2_pe.deduplicated.sorted.bam

Work dir:
  /tmp/wr_cwd/8/0/3/83ffa1ab79fa53d119320d4e6e069870891302/cwd/work/34/099bd83317d4c063aa0bdde9c49929

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
[nf-core/methylseq] Pipeline Complete
WARN: Killing pending tasks (1)
```

**Comment by ewels** [comment]
Hi @sb43,

Thanks for reporting this. I guess that it's not that samtools is being inefficient, but more that we're telling samtools to use _exactly_ the amount of memory available, to the byte:

https://github.com/nf-core/methylseq/blob/1d3f5cc5898c973832722a7e76538eab0933b3f5/main.nf#L774-L777

In most computational setups, the memory allocation is a little relaxed meaning that this isn't a problem, but we have seen similar problems in other pipelines. I guess that just reducing the requested amount a little should fix the problem. In fact, @apeltzer did exactly this in the rnaseq pipeline the other day: https://github.com/nf-core/rnaseq/pull/158

Phil

**Comment by sb43** [comment]
Hi @ewels,

Shall I create custom main.nf as suggested  nf-core/rnaseq#158 , currently I am using methylseq v1.3 --with-docker using default main.nf.
OR
Have you planned a bugfix release anytime soon?

Thanks,
Shriram

**Comment by ewels** [comment]
Ok, pull-request merged. You should now be able to run this now using `nextflow run nf-core/methylseq -r dev` (the `-r dev` will pull the development version of the code). It will then go out in the next stable release, which should be relatively soon I think.

I'll close this issue now, but let me know if you hit any problems and we can reopen. Would be great to hear how you get on too!

Cheers,

Phil

**Comment by sb43** [comment]
Hi Phil,
Thanks for the quickfix, I have already tried the commit from your master branch and it worked fine.
We have now fully working methylseq pipeline implemented in openstack and [WR](https://github.com/VertebrateResequencing/wr) in our group.
Thanks for your continuous support.
Cheers,
Shriram

**Comment by ewels** [comment]
Fantastic! Thanks for letting us know.. And great that you guys are able to use this in production! 😄

I hadn't realised that you were also at the Sanger until now. Are you already in contact with @wikiselev and @micans? They're also running nf-core pipelines on your OpenStack / Kubernetes infrastructure..

**Comment by sb43** [comment]
Yes, @wikiselev shared his rnaseq implementation with me.

**Comment by micans** [comment]
Which of course is by and large nf-core/rnaseq, being forked from it. 
Some day the road will lead back ...

Stijn


On 25/03/2019 11:34, Shriram Bhosle wrote:
>
> Yes, @wikiselev 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wikiselev&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_Q&m=b5M07lsDZSFAspTnVOS1LXFWLPDCfW-QtmouRohE_00&s=KSXv_Gf3_D0k5Q2w2jj7RdCWbT4aqmfXD4iCeDwASXs&e=> 
> shared his rnaseq implementation with me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nf-2Dcore_methylseq_issues_81-23issuecomment-2D476158351&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_Q&m=b5M07lsDZSFAspTnVOS1LXFWLPDCfW-QtmouRohE_00&s=DSnj1M2DJQi2qnA3DcSTjHzc4j9digtgeJC7CVdlfgg&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNr8K2h9vGax3tm76wWDaIEWejLJ6O2ks5vaLQsgaJpZM4b2zQq&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=hInWKPd_m4PWFkdglr0s_Q&m=b5M07lsDZSFAspTnVOS1LXFWLPDCfW-QtmouRohE_00&s=9wF-i6Wqzb8aMBmupoJUA2pqN8Eif4Zxhyf-b8yLkws&e=>.
>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by suhrig** [comment]
It seems this issue has returned. I am running into the same situation where samtools sort requests exactly as much memory as was reserved for the task (or a little more), resulting in the task being killed. If I'm interpreting things correctly, the changes added in PR #82 got lost when the NextFlow configuration was split into modules. See here: https://github.com/nf-core/methylseq/blob/81f989c93e866a9b0bd0d9584e077b9b8f78affe/modules/nf-core/samtools/sort/main.nf#L24C33-L24C33
