### ISSUE TITLE
Bismark hisat2 support

### ISSUE THREAD

**Issue by kokyriakidis** [nf-core/methylseq#85]
Hello,
Could you update the pipeline with the supported hisat2 aligner in the last version of bismark?

---

_[Edit]: to-do list added by @ewels - head comment to give progress bar in issues_

* [x] bismark genome preparation
    * Add `--hisat` option
* [x] bismark
    * Add `--hisat` pipeline option
    * Add `--no-spliced-aligments` bismark flag by default if using `--hisat`
       _skimming through the bismark code, it seems that this is actually set by default_
    * Add `--spliced-aligments` pipeline option to remove the above option when using hisat.
    * Add `--known-splicesite-infile <path>` pipeline option
* [x] Add hisat2 to the conda environment
* [x] Add new channels to handle hisat2 reference genome indexes (including splice sites if given)
* [x] Make all of this work with new pipeline params
    * `--aligner bismark_hisat` would be my suggestion
    * `--spliced-aligments` and `--known-splicesite-infile`
* [x] Logging and documentation

* [x] update bismark bioconda recipe to v0.21.0
* [x] change travis file to cover hisat2 alignment

**Comment by ewels** [comment]
Good idea 👍 To-do list (mostly from the [bismark changelog](https://github.com/FelixKrueger/Bismark/blob/master/CHANGELOG.md#changelog-for-bismark-v0210)):

1. bismark genome preparation
    * Add `--hisat` option
2. bismark
    * Add `--hisat` option
    * Add `--no-spliced-aligments` option
    * Add `--known-splicesite-infile <path>` option
3. Add hisat2 to the conda environment
4. Add new channels to handle hisat2 reference genome indexes (including splice sites if given)
5. Make all of this work with new pipeline params
    * `--aligner bismark_hisat` would be my suggestion?
        * Don't really want to do `--aligner hisat` as that is a little misleading
    * `--no-spliced-aligments` and `--known-splicesite-infile` are fine to mimic I think.
5. Logging and documentation

**Comment by ewels** [comment]
May need to think if we want to tweak how Qualimap runs if we're using spliced alignments? eg. running the rnaseq module instead of bamqc. Or even using rseqc??

**Comment by kokyriakidis** [comment]
Yes! You will need to use rnaseq module in order to detect the spliced alignments. rseqc is a nice option too! You can change qualimap first and when you have time add rseqc as an additional option :)

**Comment by ewels** [comment]
Part of me wonders if this should be a separate pipeline to be honest (eg. `nf-core/rnamethylation`)...

**Comment by kokyriakidis** [comment]
As stated in the bismark docs 
```
This will create bisulfite indexes for use with HISAT2. At the time of writing, this is still largely unchartered territory, and only recommended for specialist applications such as RNA-methylation analyses or SLAM-seq type applications (see also: --slam). (Default: OFF).
```

BUT Hisat2 states:
```
HISAT2 is a fast and sensitive alignment program for mapping next-generation sequencing reads (both DNA and RNA) to a population of human genomes (as well as to a single reference genome)
```
Generally HISAT2 is a very good aligner and I want to be able to test the output between bowtie2 and HISAT2 and see the differences.

**Comment by ewels** [comment]
@felixkrueger - would you like to weigh in on this topic? Any reason _not_ to use HiSAT2 for DNA bisulfite  analysis?

**Comment by FelixKrueger** [comment]
Hi all,

In my experience, HISAT2 is indeed a very good and fast aligner which is supposed to work for both DNA as well as RNA alignments. For aligning standard BS-seq I would definitely suggest using the `--no-spliced-alignments` option as there is no reason why one should assume spliced mapping for standard libraries (which would then also not require specific RNA-seq specific QC steps).

I don't have any definitive reason for *not* using HISAT2 for standard DNA alignments, but:
- Bowtie2 is well tried and tested
- we personally have not tested HISAT2 alignments just yet
- HISAT2 has still has quite a few issues/comments/feature requests open on Github, and the team has not had too much time for support over the past years (even though they assured me that this is going to change soon)

But all-in-all, I think it would be great if someone could run some comparisons so we can all be a bit more confident! Let me know if if I can be of any help.

**Comment by ewels** [comment]
Thanks! ok, so maybe have `--no-spliced-aligments` there by default and have a `--spliced-aligments` pipeline flag to remove this...

Perhaps later we can add an `--rna` mode which would then switch the QC steps, but for now I think this is a little premature and we can assume that all users are working with DNA data only.

**Comment by FelixKrueger** [comment]
Sounds like a good plan. Happy to hear any feedback, and/or option requests.

**Comment by ewels** [comment]
ok great.. I added a checklist to the initial comment to give us a progress bar in the issues 😉

**Comment by kokyriakidis** [comment]
Hi all, @FelixKrueger @ewels 

I tried to run the pipeline with some data, but I had no idea about how they have been produced. I know just that they are methylation data. SO when fastqc run, I saw that they have bad quality at the end. I wonder if trim galore should have an option in this pipeline to cut bases by quality (5' and 3' Trimming) instead of just raw bases.

**Comment by ewels** [comment]
Please try to keep issues on a single topic. I've moved your question to a new issue :)

**Comment by kokyriakidis** [comment]
> Please try to keep issues on a single topic. I've moved your question to a new issue :)

I am so sorry! Won't happen again! :)
