### ISSUE TITLE
Look in to BitMapperBS

### ISSUE THREAD

**Issue by ewels** [nf-core/methylseq#86]
You may also want to look in to BitMapperBS, a new methylation calling tool, which seems very interesting given the Time and Sensitivity improvements over the other tools. Check the paper at the results section.
https://www.biorxiv.org/content/biorxiv/early/2018/10/14/442798.full.pdf

https://github.com/chhylp123/BitMapperBS

_Originally posted by @kokyriakidis in https://github.com/nf-core/methylseq/issues/85#issuecomment-475853150_

**Comment by realzhang** [comment]
BitMapperBS is fantastic and extremely fast.
Ten fold or more? I do not have a precise comparison.
But unfortunately, it seems BitMapperBS is out of maintenance.

**Comment by sateeshperi** [comment]
bitmapper last commit was 5yrs ago. closing this request
