### ISSUE TITLE
Support for multiple samples 

### ISSUE THREAD

**Issue by kokyriakidis** [nf-core/methylseq#88]
It would be a good idea to support multiple samples so the user does not need to run the same command many times. I have 40 samples to analyse now and I have to run the command 40 times

**Comment by ewels** [comment]
Hi @kokyriakidis,

The pipeline already supports multiple samples. Just specify a pattern that matches all files. See the documentation here: https://github.com/nf-core/methylseq/blob/master/docs/usage.md#--reads

Let me know if you're facing difficulties,

Phil
