### ISSUE TITLE
Max CPU utilization

### ISSUE THREAD

**Issue by kokyriakidis** [nf-core/methylseq#89]
Hello,
whatever the configuration (even when I set max_cpus 20) bismark will run on 1 core. How can I change that?

**Comment by ewels** [comment]
Hi @kokyriakidis,

The way that bismark align uses cpus is a little complex and also depends on the memory you have available. I have a couple of questions:

* What version of the pipeline are you using?
* How much memory do you have available?
* What is the bismark command that is being generated?

This is the code that sets up bismark multicore usage:
https://github.com/nf-core/methylseq/blob/1d3f5cc5898c973832722a7e76538eab0933b3f5/main.nf#L404-L426

**Comment by kokyriakidis** [comment]
1) I am using the latest release 

2) I have 50 GB available

3) I will look into it

**Comment by ewels** [comment]
Ok, so if you have 20 cpus available and 50GB memory, according to the code above you should be able to run with `--multicore 3` I think (which would use up to 9 cpus, confusingly). The [base config](https://github.com/nf-core/methylseq/blob/1d3f5cc5898c973832722a7e76538eab0933b3f5/conf/base.config#L35-L39) should allow for this.

You should be able to see the final bismark command either in the work directory in `.command.sh` or in the workflow HTML report (in the table at the bottom).

What is the command that you're using to run the pipeline? Are you using a custom config file?

Thanks,

Phil

**Comment by kokyriakidis** [comment]
I am running with the default standard profile. Just changed max_cpus and max_memory on base.config (20 and 50 accordingly). But I do not use 9 cores for sure. Just 1 core.

I am running:
```
nextflow run methylseq/main.nf -with-singularity -profile standard --genome GRCh38 --reads '/home/kokyriakidis/Desktop/meth2/data/*_R{1,2}_001.fastq.gz' --saveAlignedIntermediates
```

**Comment by ewels** [comment]
Ok - were you able to find the `bismark` command that is being generated? eg: going to the work directory with the job hash for the alignment step and looking at `.command.sh`:

```bash
# ...launch nextflow...
[b4/82f3cf] Submitted process > bismark_align

$ cd work/b4/82f3cff7209256830b04d2ecfff709/

$ cat .command.sh
```

**Comment by bazyliszek** [comment]
CPU utilization is an interesting thema here. I asume that not adding  -profile standard in the pipeline will just call the standard profile anyway?  If so, I have opposite issue. By limmiting max_memory to 64GB and max_cpu to 5 I thought I will limit the use of memory on HPC. We have 32 CPUs and 500 GB RAM.  I see a huge peak of RAM usage, allready when fastqc is beeing run. I would like to have a full control of memory usage. Any advice?
code: 
nextflow run methylseq-1.3 -resume --max_memory 64.GB --max_cpus 5 --max_time 200.h --reads '/data/*_R{1,2}_*.fastq.gz' --outdir . --fasta references/Homo_sapiens/UCSC/hg38/Sequence/ --bismark_index references/Homo_sapiens/UCSC/hg38/Sequence/BismarkIndex/ --accel --saveTrimmed --saveAlignedIntermediates 
Cheers, bazyl

**Comment by ewels** [comment]
> I assume that not adding `-profile standard` in the pipeline will just call the standard profile anyway?

If you don't load any profiles, then that's the same as using `-profile standard`. But if you use `-profile docker` for example, it won't load the `standard` profile. 

Note that we have removed the `standard` profile in the upcoming release of the pipeline:
https://github.com/nf-core/methylseq/blob/31bf8fa76f0086e8b3705b86cd6cd8619b55307e/nextflow.config#L79-L86

> I thought I will limit the use of memory on HPC

Doing `--max_memory 64GB` should mean that no single job is able to request more than 64GB memory. If your cluster has 500GB memory, it could be that you have 7 jobs all requesting ~64GB memory each, which would still use loads of memory.

FastQC uses the [default memory config](https://github.com/nf-core/methylseq/blob/1d3f5cc5898c973832722a7e76538eab0933b3f5/conf/base.config#L17) though, which requests 8GB memory. So to saturate 500GB memory you'd need 62 instances of FastQC running in parallel (entirely possible).

I'm not sure that it's possible to set a ceiling for the entire pipeline, though you can limit the number of concurrent job submissions using nextflow.

I hope this makes sense!

Phil

**Comment by kokyriakidis** [comment]
What does  check_max( 8.GB * task.attempt, 'memory') mean and what the
numbers here errorStrategy = { task.exitStatus in [1,143,137,104,134,139] ?
'retry' : 'terminate' }

Στις Παρ, 14 Ιουν 2019 στις 1:30 μ.μ., ο/η Phil Ewels <
notifications@github.com> έγραψε:

**Comment by ewels** [comment]
`check_max` calls [this function](https://github.com/nf-core/methylseq/blob/1d3f5cc5898c973832722a7e76538eab0933b3f5/nextflow.config#L107-L138) and requests `8 GB` memory for that process _unless_ `max_memory` is less than `8 GB` (in which case, it will take that ceiling limit instead). `task.attempt` refers to processes that have been restarted due to failure - so if it fails due to running out of memory and is restarted, it will request `16 GB` instead.

`errorStrategy` is a core nextflow feature: https://www.nextflow.io/docs/latest/process.html#errorstrategy - those error codes are common error codes for HPCs killing jobs because they are running out or resources. If a job fails with one of them, it will be retried. Otherwise, the pipeline will be terminated.

**Comment by kokyriakidis** [comment]
Thank you very much for this description!

Στις Παρ, 14 Ιουν 2019 στις 2:17 μμ ο χρήστης Phil Ewels <
notifications@github.com> έγραψε:

**Comment by ewels** [comment]
Are we ok to close this issue now, or do you believe that there is an outstanding problem with the pipeline?

Note that it's best for ask for help related to running the pipeline on the nf-core Slack organisation. You can get an invite from https://nf-co.re (direct link [here](https://nf-core-invite.herokuapp.com/)).

**Comment by kokyriakidis** [comment]
Perfect thanks!

Στις Παρ, 14 Ιουν 2019 στις 3:44 μ.μ., ο/η Phil Ewels <
notifications@github.com> έγραψε:
